### ISSUE TITLE
GSON Views and RestfulController Interop

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-views#10]
When using angular or rest-api profile types where you want to leverage gson views, when using RestfulController the default view resolution for `RestfulController` save method is `save.gson`.  This is not created during gson view generation and it not listed in docs anywhere.  I discovered this via trial and error.

The save action could:
1. Render the `show.gson` for the saved object
2. Continue to render `save.gson` but add some docs and/or generation for this artifact during generate-views

**Comment by jeffbrown** [comment]
I think it should render `show.gson`.

**Comment by graemerocher** [comment]
This seems a bug / inconsistency with regards to `RestfulController`. The generated controller by scaffolding does:

https://github.com/grails/grails-profile-repository/blob/master/profiles/rest-api/templates/artifacts/scaffolding/Controller.groovy#L37

Whilst `RestfulController` does:

https://github.com/grails/grails-core/blob/master/grails-plugin-rest/src/main/groovy/grails/rest/RestfulController.groovy#L114
