### ISSUE TITLE
Use object type as model variable name in addition to template name

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-views#105]
Currently if you have:

      List<Foo> foos

And you do

     json tmpl.another(foos)

It assumes the name of the model variable is the same as the template. In this case `another`, so if you define:

      @Field Foo foo

Then `foo` will be `null` unless it is renamed to `another`. This can be confusing for users, so we should support the case of setting the variable name to the object type as well.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-views/commit/38bbaa1df96e77b9c62617a9c495e079abdfb90f
