### ISSUE TITLE
When rendering collections, view resolution should differentiate between `null` value and missing key

### ISSUE THREAD

**Issue by gregopet** [grails/grails-views#108]
If I want to render the template `authors g.render(template:'/author/short', var: 'author', collection: book.authors)` where `book.authors == null`, the `/author/short` template will get rendered once with a `author == null` variable which is probably not what the programmer intended.

If there is a possibility of a null collection the proper solution is to use `authors g.render(template:'/author/short', var: 'author', collection: book.authors ?: [])` but it is somewhat unintuitive and failure to so can lead to some head scratching.

Perhaps a `containsKey` check could be performed on the arguments map and if it does contain a `collection` parameter, treat all falsy values the same? I can't see much relevant harm coming from such a change (e.g. users knowingly supplying possible `null` to this parameter and then detecting in the template whether an instance was provided or not).

**Comment by jameskleeh** [comment]
I think one could argue the other way too that passing in a null collection results in an empty list. In the context of a POGO developers could rely on the difference between null and an empty list and this change would prevent them from doing so.

**Comment by gregopet** [comment]
...perhaps, though personally I would prefer to keep the null vs. empty array decision in the template itself, because it is a part of the API contract which the view fulfills. Tastes aside, the current code does not this: it calls a template intended to be called with _single entities_ with an _entity collection_ (that sadly also happens to be `null`), almost certainly causing a null pointer exception.

**Comment by jameskleeh** [comment]
@graemerocher Thoughts?

**Comment by graemerocher** [comment]
Maybe I'm not fully understanding the issue, from the last comment the behaviour doesn't sound right. Maybe uploading an example demonstrating the issue would help.

**Comment by gregopet** [comment]
Here's a unit test that currently passes in the `views-json` module (I can make a pull request, though perhaps it's easier to debate here):

```groovy
void "Rendering a null collection should not call the single-item template"() {
    given:"A collection"
    def ages = input

    when:"A collection type is rendered"
    def renderResult = render(''' \
        import groovy.transform.*
        import grails.plugin.json.view.*

        @Field Collection<Integer> ages

        json g.render(template:'child', collection: ages, var:'age')
    '''.stripIndent(), [ages:ages])

    then:"The result is an array"
    renderResult.jsonText == response

    where:
    input | response
    [4]   | '[{"name":"Fred","age":4}]'   // normal case
    []    | '[]'                          // empty collection does not invoke the template
    null  | '{"name":"Fred","age":null}'  // null does invoke the template and poor Fred is of age null, is also not in array
}
```

I contend that the null-handling behaviour is wrong:
 - result is not an array, even though we passed in a `Collection`
 - the template for rendering a single child got invoked, with `age == null` - high potential for null object exceptions
 - rendering `null`, `[]` or throwing an explicit exception would all be preferable to the current behaviour

@jameskleeh suggested that POGOs could rely on the difference between `[]` and `null` in collections but I think that is something to be be handled by authors individually (and very easily with Grails Views, as opposed to some other templating languages, e.g.

```
if (ages == null) {...}
else if (ages.size() == 0) {..}
else {...} 
```

**Comment by jameskleeh** [comment]
What does the child template contain?

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-views/commit/9248e6d16efbfeaa3a221d16101ede8026fc1989

**Comment by gregopet** [comment]
It's a template from the unit tests, https://github.com/grails/grails-views/blob/master/json/grails-app/views/_child.gson

Now that I think of it, personally I would be ok with either an empty array or a `null`, as long as the template is not rendered with null values because it is sneaky and makes you look for the wrong causes when a null creeps in either in a unit test or simply in production when a null sneaks in.

**Comment by gregopet** [comment]
Ah, fixed while I was typing :) Thank you, it's a small thing but I think it will help people not wonder what's going on :)
