### ISSUE TITLE
HAL pagination links don't follow URL mappings 

### ISSUE THREAD

**Issue by ZacharyKlein** [grails/grails-views#109]
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a domain class, restful controller, and a JSON view that uses `hal.paginate()` 
2. Specify a resource mapping in `UrlMappings.groovy`
3. Browse to the view (see the sample project) - e.g, `/api/product

### Expected Behaviour

The pagination links should display next/previous links using the `api/product` URL pattern

### Actual Behaviour
The pagination links 1. fall back to the default `$controller/$action/*` mapping, or 2. (if default mapping is not present, such as in the `rest-api` profileAdd), render the full classname of the domain class in the URL:  ````http://localhost:8080/class+com.example.Product/index?offset=0&max=10````

### Environment Information

- **Operating System**: macOS
- **Grails Version:** 3.2.5
- **JDK Version:** 1.8

### Example Application

- https://github.com/ZacharyKlein/json-paginate-urls

**Comment by sdelamo** [comment]
Same problem if the custom uri is defined with the `@Resource(uri: )` 

Inside this repository https://github.com/grails-guides/using-hal-with-json-views 

in the folder `complete`

There is a Grails App.

Same failing unit tests illustrate this problem: 

`OrderShowV2Spec.groovy`
`OrderShowV3Spec.groovy`
`ProductListSpec.groovy`

**Comment by jameskleeh** [comment]
This is a core issue, so I created an issue in grails-core. https://github.com/grails/grails-core/issues/10472

**Comment by jameskleeh** [comment]
Fixed by grails/grails-core@9132200
