### ISSUE TITLE
JSON Model naming convention isn't consistent

### ISSUE THREAD

**Issue by KerchumA222** [grails/grails-views#112]
By convention, models in JSON views are based on their types
For example: `List<String> stringList` works.
But, in templates they are based on the template name.
(in _msg.gson) `String msg` works, but `String string` doesn't. 

I think these should be handled in a consistent way, either by always using the type based names, always using the view/template names, or some other way.

I have created a sample project with examples of the way it currently works, as well as non-working examples that I believe should work: https://github.com/KerchumA222/GrailsJsonViewModelNaming

**Comment by jameskleeh** [comment]
When rendering a template with a collection, `String string` should work in the template. That was a change that was made recently

**Comment by KerchumA222** [comment]
I just tried 1.1.4; it works when calling `tmpl.msg()` on a single item, but when using a collection it still uses the template name only.

**Comment by jameskleeh** [comment]
Did you update the example app?

**Comment by KerchumA222** [comment]
I did not push my update to it. I can if you'd like; that way, you can also
see what I am seeing.

**Comment by jameskleeh** [comment]
Yeah please do

**Comment by KerchumA222** [comment]
I pushed. I actually had a mistake (I only updated the version in the `classpath` block, not the dependencies block) and it seems to all be working correctly now. Thanks again.
