### ISSUE TITLE
Hal embeed not rendering in JsonViewTests

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-views#114]
Inside this repository https://github.com/grails-guides/using-hal-with-json-views

in the folder `complete`. There is a Grails App.

if you run the app in development environment and visit `localhost:8080/api/products/1`HAL embeed appears. 

However, it fails when the GSON view is rendered inside a Unit tests implementing `JsonViewTest`.

Same failing unit tests illustrate this problem:

`OrderShowV4Spec.groovy`
`ProductShowSpec.groovy`

**Comment by jameskleeh** [comment]
You need to added the domains to the mapping context
