### ISSUE TITLE
Self relation gson rendering not working with web profile

### ISSUE THREAD

**Issue by koctob** [grails/grails-views#122]
If I want to render self referring structure I got exception in web profile:
**Circular view render occurred for view** - because of [deep:true]
In case or restful profile everything is working fine - even without deep: true.

I tried to transfer everything from the restful profile to the web -> domain, controller, dependencies -without success.

**Details**

Using grails 3.2
views : 1.2.x
profiles: web and restful

Desired result:
N1{N2,N3{N4...

**Domain**

class Node {
    String name
    String data
    String relation
    Book book
    static hasMany = [children: Node]

My gson:

**node.gson**

import json.Node

model {
    Node node
}

json tmpl.node(node)

**_node.gson**

import json.Node

model {
    Node node
}

json {
    //data node.data
    id node.id
    data(relation: node.relation)
    name node.name
    children g.render(node.children)
}

**Comment by jameskleeh** [comment]
Please upload an example project
