### ISSUE TITLE
JSON API Support incompatible with grails.rest.RestfulController

### ISSUE THREAD

**Issue by ivarprudnikov** [grails/grails-views#123]
In `RestfulController.index` method `respond` is called the following way:

`respond listAllResources(params), model: [("${resourceName}Count".toString()): countResources()]`

Which is responding with a List of entities and at the same time adding entityCount variable to the rendered model.

In a [`respond` documentation](https://docs.grails.org/latest/ref/Controllers/respond.html) `model` argument is described as: _The model to use in case of HTML rendering_

Because total count of entities is exposed to HTML model and not to JSON, then it is not possible to define pagination in a `*.gson` view, eg:

`book/index.gson`
```
import groovy.transform.Field
import my.package.Book

@Field List<Book> bookList = []
@Field Integer bookCount // <== this is not exposed

json jsonapi.render(bookList, [meta:[bookCount],pagination: [total: bookCount, resource: Book]])
```

The only solution here is not to use default RestfulController or `@Resource` annotation on a domain class, but instead create similar controller which will expose model as a Map.

-----

Grails version: v3.2.9
Grails Views: v1.2.1

**Comment by jameskleeh** [comment]
So what is the issue? RestfulController does not dictate you must use gson views. The solution you proposed seems like the right one to me. You can easily override the index action.

**Comment by ivarprudnikov** [comment]
From my point of view Grails has some conventions on how to use bits of its features, `@Resource` and `RestfulController` are used in [documentation](https://docs.grails.org/latest/guide/single.html), json views mentioned as well, marshallers are deprecated.

Then you go and try using your documentation http://views.grails.org/ and there is very little about the way binding of model actually happens, everything is in bits and pieces, but no real world example.

I suggest making explicit statement that plugin is not compatible with `@Resource` annotation for instance as this is what you would use in a microservice by default.

Major factor for opening this issue is confusion which was caused by documentation and lack of real world examples.

**Comment by jameskleeh** [comment]
@ivarprudnikov JSON views work with the`@Resource` annotation, just not exactly as you would like.

You are welcome to submit a PR to the documentation to include real world examples.
