### ISSUE TITLE
JSON views not working with namespacing convention

### ISSUE THREAD

**Issue by raydawg2000** [grails/grails-views#125]
Typical non-json template rendering uses naming convention to locate views, but I cannot get this to work with JSON Views.

**Sample class**

    class StrainsController extends ManagerController {
        static namespace = "manager";

        def edit() {
            def model = []
            respond(model, view: "/manager/strains/edit")
        }
    }

**Folder Structure**

    grails-app
      views
        manager
          strains
            edit.gson

If I omit the view specification I get the following exception:
`javax.servlet.ServletException: Could not resolve view with name 'edit' in servlet with name 'grailsDispatcherServlet'`

Ideally I shouldn't have to explicitly define where my gson view is located, Grails convention over configuration motto should already handle it.  What do I need to do to enable this to work?

Grails 3.2.8
JSON Views 1.2.3

**Comment by jameskleeh** [comment]
We have tests that prove this is working https://github.com/grails/grails-views/blob/master/functional-tests/src/integration-test/groovy/functional/tests/api/NamespacedBookSpec.groovy. Instead of showing what is working, give me an example of what isn't working.

**Comment by raydawg2000** [comment]
Great thank you, here is my test showing that is not working for me

1.  Create app.  **Project:** [namespace.zip](https://github.com/grails/grails-views/files/1092544/namespace.zip)
2.  Add required views library to `build.gradle` as per documentation
3.  Create Test controller with namespace

```
class TestController {
    static namespace = "manager";

    def edit() {
        def model = []
        //respond(model, view: "/manager/test/edit")
        respond(model)
    }
}
```
4.  Create edit.gson in grails-app/views/manager/test/
5.  ***Optional*** Update UrlMappings to respond to namespace in URL.  Issue happened whether I did this or not.

```
"/manager/$controller/$action?/$id?(.$format)?"{
    namespace = "manager"
    constraints { }
}
```
6.  Run app and visit URL (Depends on if you updated UrlMappings or not.)
http://localhost:8080/test/edit 
http://localhost:8080/manager/test/edit

7.  Watch exceptions appear on screen
```
javax.servlet.ServletException: Could not resolve view with name 'edit' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1262)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
....

```

8.  Go to `TestController` and change `respond` to explicitly give the view path and it works as expected.

My expectation is that based on this setup, I should not have to explicitly define the view path.  The naming convention nature of Grails should already know how to find my view.

Please let me know if you have any more questions.

**Comment by jameskleeh** [comment]
You need to specify response formats when using `respond`. Add `static responseFormats = ['json']` to your controller
