### ISSUE TITLE
Display garbled character after running long time

### ISSUE THREAD

**Issue by vincechan15** [grails/grails-views#126]
After Grails 3 application running for few days, the web site start randomly display garbled character for German language. For example über is displayed as ��ber. The request is not always returning garbled character, but after few request made and return the correct character on next request.

Please refer to [stackoverflow](https://stackoverflow.com/questions/45453614/grails-3-display-garbled-character-after-running-long-time) for details

**Comment by jameskleeh** [comment]
Please upload an example project with steps to reproduce

**Comment by vincechan15** [comment]
It is show random behavior and we cannot reproduce the issue

**Comment by jameskleeh** [comment]
Without the ability to test locally, Im afraid there isn't anything I can do.
