### ISSUE TITLE
Domain object in Iterable only works in default template name - only shows the first, otherwise

### ISSUE THREAD

**Issue by jksaunders** [grails/grails-views#128]
Sorry for the confusing title - I wasn't sure how to capture the scenario in one line.

I have a controller that responds with a list of User objects (standard attributes: username, password, etc.).

The following is the corresponding .gson file for that controller action:

**index.gson**
```
model {
    List<User> users
}

json {
    users tmpl.'../user/user'(users)
}
```

The following the `user` template being called above:

**_user.gson**
```
model {
    User user
}

json g.render(user, [excludes: ['accountsAdministrated', 'password']])
```

Now when the action is called, this is the JSON output:
```
{
    "users": [
        {
            "id": 1,
            "passwordExpired": false,
            "username": "me",
            "accountLocked": false,
            "accountExpired": false,
            "enabled": true
        },
        {
            "id": 2,
            "passwordExpired": false,
            "username": "me2",
            "accountLocked": false,
            "accountExpired": false,
            "enabled": true
        }
    ]
}
```

Now I have another `.gson` file called `_userTest.gson`, that is the **exact same** content as `_user.gson`. When I change `index.gson` to use `users tmpl.'../user/userTest'(users)`, despite that it's the exact same content, here's the following JSON output:

```
{
    "users": [
        {
            "id": 1,
            "passwordExpired": false,
            "username": "me",
            "accountLocked": false,
            "accountExpired": false,
            "enabled": true
        },
        {
            "id": 1,
            "passwordExpired": false,
            "username": "me",
            "accountLocked": false,
            "accountExpired": false,
            "enabled": true
        }
    ]
}
```

As can be seen above, it's the exact same user twice. I can't figure out why this is happening. Any ideas?

**Comment by jameskleeh** [comment]
Please upload an example project

**Comment by jameskleeh** [comment]
Closing due to lack of example
