### ISSUE TITLE
Error resolving views in deployed application

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-views#13]
When running locally using bootRun, all works well.  However when deploying the application as a jar and using java -jar foo.jar the application is failing to resolve views that are in a common directory.  This appears to be something in or around the cache returning back a resolvable template cache that doesn't actually have the template in there at [this line](https://github.com/grails/grails-views/blob/21578f15cd235003f8122cc3d65eec703a33f01b/core/src/main/groovy/grails/views/ResolvableGroovyTemplateEngine.groovy#L231)

<img width="308" alt="screen shot 2016-04-01 at 10 33 26 am" src="https://cloud.githubusercontent.com/assets/691357/14212322/f723b206-f7f7-11e5-829a-bf31ac65f16b.png">

<img width="801" alt="screen shot 2016-04-01 at 10 33 36 am" src="https://cloud.githubusercontent.com/assets/691357/14212327/fb525b66-f7f7-11e5-9edd-eeb418df7ea6.png">

<img width="844" alt="screen shot 2016-04-01 at 10 43 05 am" src="https://cloud.githubusercontent.com/assets/691357/14212333/006c877a-f7f8-11e5-968f-1c72d0d8e8c1.png">

<img width="1116" alt="screen shot 2016-04-01 at 10 44 53 am" src="https://cloud.githubusercontent.com/assets/691357/14212336/0450e4d0-f7f8-11e5-962f-ef77b6eb1712.png">

When disabling the cache via

``` yml
---
grails:
    views:
        json:
            compileStatic: true
            cache: false
```

the issue is still present because the cache is not actually being disabled when running the jar.  See issue #12

**Comment by ctoestreich** [comment]
I can not reproduce with a new project using profile rest-api.  The above project is using the angular profile.

**Comment by ctoestreich** [comment]
When switching the profile to `profile "org.grails.profiles:rest-api:3.1.4"` from `profile "org.grails.profiles:angular:3.1.4"` this appears to work.  I am not sure why the angular profile would be broken, but this is probably intended to work via angular profile as using gson views is preferred.

**Comment by graemerocher** [comment]
Please upload an example that reproduces the problem

**Comment by ctoestreich** [comment]
Still working on getting it to break in simple project.

**Comment by ctoestreich** [comment]
It very well might be something with our code as we have a complex scenario, but it would appear that ultimately the show.gson view for a domain class `Site` using a `SiteAdminController` via `/stieAdmin/show.gson` is asking for all the templates and it has put in a `class grails.views.ResolvableGroovyTemplateEngine` in the concurrent hash cache value for key `/templates/common/_site.gson` for the view upon initially loading the show.gson.  When then asking for the actual `/templates/common/_site.gson` it is essentially returning back this "null" reference when it sees the item in the hashmap and runs line 233 of ResolvableGroovyTemplateEngine.groovy the next time through.

``` java
if(template.is(NULL_ENTRY)) {
    return null
}
```
<img width="1460" alt="screen shot 2016-04-04 at 11 27 29 am" src="https://cloud.githubusercontent.com/assets/691357/14255274/d29e84ac-fa58-11e5-92fa-be8fb5854698.png">

When stepping through in more detail it appears some other thread is creating a null entry before the resolvablegroovytemplateengine actually evaluates the template.

The cachedTemplates has 4 entries for the show.gson and then when running over this code and existing to evaluate the template there is a magically 5th entry by this time

``` java
if(shouldCache) {
            template = resolveCache.get(cacheKey)
            if(template != null) {
                if(template.is(NULL_ENTRY)) {
                    return null
                }
                else if(!((GrailsViewTemplate)template).wasModified()) {
                    return template
                }
                else {
                    cachedTemplates.remove(path)
                    resolveCache.remove(cacheKey)
                    template = null
                }
            }
        }
```

<img width="1355" alt="screen shot 2016-04-04 at 12 13 37 pm" src="https://cloud.githubusercontent.com/assets/691357/14256548/227231f8-fa5f-11e5-91cb-6d0bc87f1c96.png">

I am going to try and enable the new feature in intellij to only resume current thread to see if it is indeed a background thread.

**Comment by ctoestreich** [comment]
Something with this [line](https://github.com/grails/grails-views/blob/21578f15cd235003f8122cc3d65eec703a33f01b/core/src/main/groovy/grails/views/ResolvableGroovyTemplateEngine.groovy#L251)  is putting an entry into the cachedTemplates.

Two examples:

<img width="1292" alt="screen shot 2016-04-04 at 12 30 01 pm" src="https://cloud.githubusercontent.com/assets/691357/14256983/058f0e42-fa61-11e5-9239-b848fddcaf3e.png">
 
<img width="1292" alt="screen shot 2016-04-04 at 12 30 01 pm" src="https://cloud.githubusercontent.com/assets/691357/14256986/098340e0-fa61-11e5-802a-a79d31db4ac7.png">

**Comment by ctoestreich** [comment]
I can only see a single thread in the template engine code.

<img width="1828" alt="screen shot 2016-04-04 at 12 33 34 pm" src="https://cloud.githubusercontent.com/assets/691357/14257077/8a48ed2e-fa61-11e5-8538-0a2d3458db3e.png">

**Comment by ctoestreich** [comment]
The other oddity is that there are break points on the withDefault so and those are not getting hit when the entry is created.

<img width="893" alt="screen shot 2016-04-04 at 12 42 58 pm" src="https://cloud.githubusercontent.com/assets/691357/14257311/dc1fab6e-fa62-11e5-83e8-bf624b9af5ee.png">

**Comment by ctoestreich** [comment]
@graemerocher I was able to boil down the issue to the following, but I have no idea why this is happening.

For some odd reason, these particular GSON views are compiling into the . directory where the others are in the / directory.

We are simply running ./gradlew :bsb-content-service:assemble from the root of a gradle multi project.  That appears to be the secret sauce.  I will create a demo project and see if I can recreate that way.  The common shared piece of the puzzle may be that the artifacts are prefixed with _site*?

[Video Link](https://vimeo.com/161511826)

![screen shot 2016-04-04 at 1 05 22 pm](https://cloud.githubusercontent.com/assets/691357/14258201/f827cb08-fa66-11e5-95af-5b58b422e8b8.png)

**Comment by ctoestreich** [comment]
The best I can do is partially recreate here with this branch

https://github.com/Grails-Plugin-Consortium/grails-gson-views/tree/multi-project

**Comment by ctoestreich** [comment]
The work around for now (and a dirty one at that)

``` gradle
task copyClasses(type: Copy) {
    from 'build/gson-classes/main/templates/common'
    into 'build/gson-classes/main'
}

assemble.dependsOn copyClasses
copyClasses.dependsOn compileGsonViews
```

**Comment by graemerocher** [comment]
@ctoestreich The reason for this is you have package statements in your GSON views:

```
package templates.common
```

Removing these statements fixes the problem.
