### ISSUE TITLE
default for _iterable.gson

### ISSUE THREAD

**Issue by basejump** [grails/grails-views#130]
It does not appear that a clean way to specify a default way to process a list. 

Use Case:
We have 100+ domains and 80 of them can use a standardized default way processing both the list with pagination and the domain without having to go in and specify an index.gson or a template under /views/{domainName}

if we could have the ability to put a default for /object/_iterable.gson
 
```
model {
    Iterable objectList //TODO naming here?
    Integer dataCount
    Integer max
    Integer offset
    String sort
    String order
}

response.contentType "application/hal+json"

json {
    hal.paginate(dataCount, offset, max, sort, order)
    g.render(objectList)
    count productCount
    max max
    offset offset
    sort sort
    order order
}
```

and then when/if a domain needs to change the default way of handling pagination it can override similar to what happens _object.gson -> _book.gson

Is there a better way to specify a standard way to  I am missing on this that would not break DRY?

**Comment by jameskleeh** [comment]
Couldn't you just use the `_object.gson` and check if the object is an Iterable? Then if it is render a template.

**Comment by jameskleeh** [comment]
Closing due to lack of feedback

**Comment by basejump** [comment]
@jameskleeh I am just getting back to this. I am confused as to how to keep things DRY here. is there an example anywhere the best way to accomplish the above so that we can have just one default gson or whatever to specify pagination?
