### ISSUE TITLE
Rendering of null fields

### ISSUE THREAD

**Issue by immutability** [grails/grails-views#132]
While trying to migrate an existing app from JSON marshallers to JSON views, I noticed a difference in JSON rendering when it comes to null fields of domain objects. Imagine a User object with firstName, lastName and middleName fields, with the middleName being null. With our JSON marshallers, this would produce the following JSON: `{ "firstName": "John", "middleName": null, "lastName": "Doe" }`

With a simple GSON view:
```groovy
model {
    User u
}
json g.render(u)
```

The JSON output produced is: `{ "firstName": "John", "lastName": "Doe" }`

I realize this doesn't make much difference but it has some implications for our existing app. I was wondering if it's possible (or if it could be introduced as an option) to fine-tune rendering of null fields so that they would be rendered in the JSON output with a null value rather than omitted? Or perhaps there is a way already that I didn't find in the docs? I'm testing on Grails 3.1.x with JSON Views 1.2.3.

**Comment by jameskleeh** [comment]
Added a `renderNulls` option to `g.render` https://github.com/grails/grails-views/commit/3977f2ce9d0ea48c184b64c02fcecc5c9261227d
