### ISSUE TITLE
_object.gson support appears to not be working

### ISSUE THREAD

**Issue by cfsilence** [grails/grails-views#133]
Please see this repo:

[https://github.com/cfsilence/grails-views-test](https://github.com/cfsilence/grails-views-test)

My assumption, based on the documentation, is that hitting http://localhost/test/test would render the Map as JSON by falling back to the object/_object.gson template, but when I hit that URL I receive an exception:

Could not resolve new with name 'test' in servlet with name 'grailsDispatcherServlet'.

Am I misunderstanding the _object.gson support or shouldn't it try to render the JSON with _object.gson since I haven't defined a test.gson template?

**Comment by jameskleeh** [comment]
Add `static responseFormats = ['json']` to your controller

**Comment by cfsilence** [comment]
Thanks.  Did I miss this in the documentation?

**Comment by jameskleeh** [comment]
@cfsilence Yes you did: http://docs.grails.org/latest/guide/theWebLayer.html#jsonResponses
