### ISSUE TITLE
Nested Expand Support

### ISSUE THREAD

**Issue by mitch2na** [grails/grails-views#134]
Currently views can't support  nested expand and finding a template for a java assist proxy object.

**Comment by jameskleeh** [comment]
You'll have to clarify the ideas you're trying to convey with example projects and steps to reproduce. Please create 1 issue per bug/feature being described.

**Comment by mitch2na** [comment]
I was going to submit a PR with the fixes, just give me a sec :)

**Comment by jameskleeh** [comment]
It is better to create an issue first to determine if a PR is appropriate. It may be that some use cases can be supported in other ways.

**Comment by mitch2na** [comment]
Okay i saw one issue that sort of addresses the problem, but didn't apply my change to JSON API specifically. That's why i just created a new one

https://github.com/grails/grails-views/issues/85
