### ISSUE TITLE
Odd issue with domain object lists and inheritance trees

### ISSUE THREAD

**Issue by immutability** [grails/grails-views#137]
I'm facing an odd issue when trying to render a JSON view with a collection that contains domain objects with inheritance. Once again I'm not sure if I'm doing it wrong or if I'm missing some critical piece, but imagine this simple model:
- Author, who hasMany books
- Book, which belongs to Author
- SpecialBook, which is a subclass of a Book

Then there's a straightforward controller action to show a single author:

```groovy   
render(view: '/api/author/show', model: [e: author])
```

There's also a "minimal" JSON template for a book located under grails-app/views/api/book/_minimal.gson:

```groovy   
model {
    Book book
}
json {
    id book.id
    name book.name
}
```

The JSON view under grails-app/views/api/author/show.gson looks like this:

```groovy
model {
    Author e
}
json g.render(e) {
    //books g.render(e.books.sort { it.id })
    books tmpl.'/api/book/minimal'(e.books)
}
```

You'll notice the render call, which is commented out. That actually works OK (but I can't include/exclude specific fields). The problem is when the template is used. If the author's collection contain's Book as well as SpecialBook instances, the SpecialBook instances will contain invalid data (previous Book's data will be repeated). Example:

```
author.addToBooks(new Book(name: 'Book 1', author: author))
author.addToBooks(new Book(name: 'Book 2', author: author))
author.addToBooks(new SpecialBook(name: 'Book 3', isbn: '1234', author: author))
```
Here's what you'd get in the books JSON:

```json
{ "id": 1, "name": "author", "books": [ 
    { "id": 1, "name": "Book 1" }, 
    { "id": 2, "name": "Book 2" }, 
    { "id": 2, "name": "Book 2" } ]
}
```

There's no exception or error, just invalid data in the JSON produced. And I'm not sure - is there a proper way around this when using domain object inheritance and named JSON templates (i.e. not the default template under views/book/_book.gson and views/specialbook/_specialbook.gson)?

I have attached a sample app (Grails 3.1.15, JSON Views 1.2.4) to demonstrate this - just run `grails test-app -unit` or you can also do a run-app and use curl to see the invalid output i.e. `curl http://localhost:8080/test/show/1`

[dominh.zip](https://github.com/grails/grails-views/files/1344810/dominh.zip) - sample Grails 3.1.15 app

**Comment by immutability** [comment]
I found 2 ways to work around the issue:
- if I place the "minimal" template for a book into the author directory and rename it to "book", i.e. grails-app/views/api/author/_book.gson then everything works OK for both, the Book and SpecialBook instances - however this approach limits code re-use if the template is to be used from multiple views
- another option is to also rename the template to "book" but place it under grails-app/views/api/book/minimal/_book.gson, this also seems to work OK and satisfies the code re-use scenario though the path is a bit too long

I'm still just learning to use JSON Views and I'm sure I don't fully understand how to use the templates properly, but the behavior when invalid data is displayed in the JSON if a subclass is encountered still looks like a bug?

**Comment by jameskleeh** [comment]
@immutability I ran the sample application you provided and called the /test/show/1 endpoint as you indicated and received: `{"id":1,"name":"rado","books":[{"id":1,"author":{"id":1},"name":"Book 1"},{"id":2,"author":{"id":1},"name":"Book 2"},{"id":3,"author":{"id":1},"isbn":"12345","name":"Book 3 (special)"}]}`. That looks to me to be the correct result.

**Comment by jameskleeh** [comment]
I see the example project had the working case by default. Example projects should show the behavior you think is incorrect out of the box so the person debugging the issue doesn't have to spend time determining how to get the issue to show.

When rendering data of different types, you need to specify the model name:

`books tmpl.'/api/book/minimal'("book", e.books)`

**Comment by immutability** [comment]
@jameskleeh Thank you for your time and help - that's the piece I was missing! 

I apologize about the test - my intent was to provide the failing case in the attached app, but I was probably a bit too tired at the end of my day, and accidentally zipped the wrong version of the file. Sorry again!
