### ISSUE TITLE
Nested inheritance produces odd result and model is not passed correctly

### ISSUE THREAD

**Issue by olliefreeman** [grails/grails-views#141]
If you have a template which calls `inherit` to another template which does the same, something very odd is happening with the generated JSON. 

Also the model passed to the top template does not map the second variable correctly, requiring the model to be specified.

`class PrimitiveType extends DataType{//...}`
```
// /primitiveType/_primitiveType.gson
inherits  template: '/dataType/dataType'
model {
    PrimitiveType primitiveType
}

json {
    if(primitiveType.units) units primitiveType.units
}
```
`class DataType extends CatalogueItem{//..}`
```
// /dataType/_dataType.gson
inherits template: '/catalogueItem/catalogueItem', model: [catalogueItem: dataType]
model {
    DataType dataType
}
json {
    type dataType.type
}
```

```
// /catalogueItem/_catalogueItem.gson
model {
    CatalogueItem catalogueItem
}
json {
    id catalogueItem.id
    label catalogueItem.label
    if(catalogueItem.description) description catalogueItem.description
}
```

Generated JSON:
```{{"id":"fc51373c-505a-4659-8d26-f863a6b9a1d5","label":"integer","type":"PrimitiveType"}}```

Without passing the model argument in `/dataType/_dataType.gson` the binding variables in `/catalogueItem/_catalogueItem.gson` are:
```2017-10-11 20:00:56,303 [080-exec-3] WARN  grails.views.AbstractWritableScript      : [primitiveType:PrimitiveType : integer : fc51373c-505a-4659-8d26-f863a6b9a1d5, org.json.views.RENDER_PROCESSED_OBJECTS:[:], dataType:PrimitiveType : integer : fc51373c-505a-4659-8d26-f863a6b9a1d5, hashMap:[:]]```

**Comment by jameskleeh** [comment]
Please include an example application
