### ISSUE TITLE
Logs are not getting displayed on terminal 

### ISSUE THREAD

**Issue by varun-kulkarni24** [grails/grails-views#146]
# Environment

Grails Version: 3.2.10

## What happens ?
I am using groovy as back end. Below is my code.

```
def getStudentName() {
        log.debug "Inside the method"
        try {
            String name = " JERRY"
            log.debug "Inside the method"
        }
        catch (Exception e) {
            log.error " Error : ${e.getLocalizedMessage()}"
        }
        log.info "Response from method :  ${name}"
        render name
    }

```
When I call this API, log.debug and log.info from this method doesn't get displayed in terminal.
If any exception occurs, log.error gets displayed in terminal. I have logback.groovy file to configure log levels.

**This is my logback.groovy**  
```
    appender('STDOUT', ConsoleAppender) {
        encoder(PatternLayoutEncoder) {
            pattern = "%level %logger - %msg%n"
        }
    }
    root(ERROR, ['STDOUT'])

    appender("PROD_LOGS", FileAppender) {
        file = "./production.log"
        append = true
        encoder(PatternLayoutEncoder) {
            pattern = "[ %d ] %level::%logger -- %msg%n"
            
        }
    }
     
    logger("StackTrace", ERROR, ['PROD_LOGS'], false)
    logger 'grails.app.controllers', ERROR, ['PROD_LOGS'], false
```

**Note :** This happens to some of the controllers from my application.
# Question
How to overcome this ?

**Comment by jameskleeh** [comment]
This issue has nothing to do with this repository, which is for views. If you want to log messages, you have to set up a logger with a logging level low enough to capture it. 

`logger 'grails.app.controllers', INFO, ['PROD_LOGS'], false`
