### ISSUE TITLE
Enum rendering for the jsonapi render method should be configurable

### ISSUE THREAD

**Issue by danielritter** [grails/grails-views#147]
I have a domain class DomainTest 
```
class DomainTest {
    String name
    String description
    EnumTest enumTest = EnumTest.VALUE_1
}
```
Also I have an enum test class:

```
enum EnumTest {

    VALUE_1("value 1"),
    VALUE_2("value 2"),
    VALUE_3("value 3")

    private String name

    private EnumTest(String name) {
        this.name = name
    }

    String getName() {
        return name
    }

    @Override
    String toString() {
        return "TEST"
    }
}
```

Then I have a _domainTest.gson file with following content:
```
import packagename.DomainTest

model {
    DomainTest domainTest
}

json jsonapi.render(domainTest, [resolveTemplate: false])
```
When I get the JSON result I get something like:
```
[
    {
        "data": {
            "type": "domainTest",
            "id": null,
            "attributes": {
                "enumTest": "VALUE_1",
                "name": "Name Test",
                "description": "Description Test."
            }
        },
        "links": {
            "self": "/domainTest/1"
        }
    }
]
```
But I want something like
```
[
    {
        "data": {
            "type": "domainTest",
            "id": null,
            "attributes": {
                "enumTest": "value 1",
                "name": "Name Test",
                "description": "Description Test."
            }
        },
        "links": {
            "self": "/domainTest/1"
        }
    }
]
```
or
```
[
    {
        "data": {
            "type": "domainTest",
            "id": null,
            "attributes": {
                "enumTest": "TEST",
                "name": "Name Test",
                "description": "Description Test."
            }
        },
        "links": {
            "self": "/domainTest/1"
        }
    }
]
```

My opinion is that jsonapi.render should be configurable how Enum's should be rendered. 

When I add 
```
        JSON.registerObjectMarshaller(Enum) { Enum e ->
            e.toString()
        }
```
to the BootStrap.groovy-File, the JSON shows correctly when I use directly `render DomainTest.list() as JSON` over a Controller, but when I want to output the JSON over the _domainTest.gson Grails View the `registerObjectMarshaller` does not attack.

**Comment by jameskleeh** [comment]
See the section on registering custom converters

http://views.grails.org/latest/#_custom_converters

**Comment by danielritter** [comment]
Thank you. But I don't get it how I can register the custom converters. Could you tell me how and where I can do that. Where can I find `src/main/resources/META-INF/services/grails.plugin.json.builder.JsonGenerator$Converter`?

Maybe the documentation can be more clearly? Thanks a lot!

**Comment by danielritter** [comment]
Ok, thanks for your reply. I have some questions. Do I have to create the file in the folder `src/main/resources/META-INF/services` or in `src/main/resources/META-INF/services/grails/plugin/json/builder`. Then I have to create a File, in my case, called JsonGeneratorEnumConverter in that folder? Is that correct? Or what does `$Converter` mean in `JsonGenerator$Converter`. Is `$Converter` a placeholder? The package name is `grails.plugin.json.builder.JsonGenerator` or `app.package.name`? Do I have to register this file as Bean under resources.groovy? Thank you for your clarity.

**Comment by danielritter** [comment]
Do you have a working example?

**Comment by jameskleeh** [comment]
The file is created in the `src/main/resources/META-INF/services` folder. The file name is `grails.plugin.json.builder.JsonGenerator$Converter`. You can not register the file as a bean because it is not possible. The file is not a class, it is just a text file.

https://github.com/grails-plugins/grails-java8/blob/master/src/main/resources/META-INF/services/grails.plugin.json.builder.JsonGenerator%24Converter

**Comment by jameskleeh** [comment]
The concept in question is Java "services". To learn more https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html

**Comment by danielritter** [comment]
Thanks a lot. That helped a lot!

**Comment by todoubaba** [comment]
@jameskleeh I encounter the same issue. 

[DefaultGrailsJsonViewHelper.processSimpleProperty](https://github.com/grails/grails-views/blob/master/json/src/main/groovy/grails/plugin/json/view/api/internal/DefaultGrailsJsonViewHelper.groovy#L670) converts all enum properties of domain object to enum name,  `JsonGenerator$Converter` has no chance to engage.
