### ISSUE TITLE
Json converters are not available when using inheritance in gson files

### ISSUE THREAD

**Issue by olliefreeman** [grails/grails-views#148]
If you add the `inherit` line to a gson file, any custom converter which extends `grails.plugin.json.builder.JsonGenerator.Converter` is no longer available and is not used when rendering the object in question. 

This is most apparent when using the grails-java8 plugin for Json converters for the "new" Java8 time objects, the converters are loaded, and under debug they are contained in the `grails.plugin.json.builder.JsonGenerator`. However it would appear that in the `grails.plugin.json.view.JsonViewWritableScript` when the closures are called a new generator is created without these converters.

Under local testing changing lines 57 and 68 (from 1.2.5) to

`new StreamingJsonBuilder.StreamingJsonDelegate(out, false, generator)`  
and 
`new StreamingJsonBuilder.StreamingJsonDelegate(out, true, generator)`

seems to solve the issue. However there are other locations where a new generator is created and I don't know if this "passing" of the current generator breaks something else further down the line.

Please see https://github.com/olliefreeman/grails-issues and the `rest.api.app.JsonGeneratorConverterAccessSpec`  (unit) test as an example.

Also not sure if just doing `TODO: When Groovy 2.4.5 go back to JsonBuilder from groovy-json` would fix the issue, but I have no idea how to implement that.

Using grails 3.3.1, grails-views 1.2.5, groovy 2.4.11, java 8u141

**Comment by jameskleeh** [comment]
Thanks for the report!

**Comment by olliefreeman** [comment]
Thanks for the fix 👍
