### ISSUE TITLE
Default access to grailsApplication

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-views#15]
I would like to reference configuration variables that are set within grailsApplication.config, but they are not available in a Domain based JSON view. There does not appear to be an ability to reference the grailsApplication within a gson view besides explicitly passing it in via a Controller method, as the ApplicationController does. It would be great if gson views could make references to the grailsApplication by default.

**Comment by graemerocher** [comment]
I'm not convinced this is a good thing to have by default, it encourages more logic in the view where the view should just render a model

**Comment by marcDeSantis** [comment]
I'm not sure what kind of logic is available via grailsApplication. In my case, I would like access to config parameters which are needed in rendering the view.

**Comment by graemerocher** [comment]
Access to `Config` seems reasonable to me

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-views/commit/0827c521c6251aaecfdffdd97ddf6283403e0f11

**Comment by jamesxabregas** [comment]
Can I suggest that this feature be added to the Grails Views documentation. It took me a while to find this issue and even then I had to review the source code to figure out that the config object is available as a property in JSON Views.
