### ISSUE TITLE
Default rendering of embedded objects

### ISSUE THREAD

**Issue by immutability** [grails/grails-views#150]
I'm not sure if this is the intended behavior, but I'm facing an issue with domain objects that contain embedded objects. With default rendering of JSON views, calling render on any domain object containing embedded objects would crash with a NullPointerException unless the embedded object fields are excluded and rendered manually (or unless you provide a default template for the embedded object in the views/objectclass/_objectclass.gson). 

On the other hand, references to other domain objects are pretty much always rendered OK even without a default template - without deep/expand they are rendered as { "id": 123 } and with the expand object, all fields get rendered. So I was wondering if something like this (as the default behavior) couldn't be implemented also for the embedded objects?

Let's take an example with a User domain class, and an Address class (located outside grails-app under src/groovy) embedded within User like this:

```groovy
User { 
    String email
    Address physical
    Address mailing
    // ...
    static embedded = ['physical', 'mailing']
}
```

And a simple view to render a single user with:

```groovy
render(view: '/api/user/show', model: [user: user])
```

The view:

```groovy
model {
    User user
}
json g.render(user)
```

This would crash with the following exceptin: 

> grails.views.ViewRenderException: Error rendering view: null] with root cause
> java.lang.NullPointerException: null

unless you provided a default template for the address under views/address/_address.gson or unless you did this:

```groovy
model {
    User user
}
json g.render(user, [excludes: ['physical', 'mailing']]) {
    physical g.render(user.physical)
    mailing g.render(user.mailing)
}
```

What do you think? I know you can always work around this by providing the default template or explicit rendering (as in the above example) but perhaps it would be worthwhile to provide default behavior for embedded objects (or perhaps exclude them by default to prevent the exception)?

**Comment by jameskleeh** [comment]
JSON views are designed to handle your use case. Please upload an example project that demonstrates the issue

**Comment by immutability** [comment]
Interestingly it would pass in a unit test, it only fails in a functional test with a REST client.

Sample app attached (Grails 3.1.15, JSON Views 1.2.6) - just run grails test-app - JsonViewSpec will pass, and JsonViewFunctionalSpec will fail. You can also do a run-app and use curl to see the exception i.e. curl http://localhost:8080/test/user/1

[embedded.zip](https://github.com/grails/grails-views/files/1499769/embedded.zip)

**Comment by jameskleeh** [comment]
@immutability That application doesn't have a valid gradle wrapper, just FYI

**Comment by jameskleeh** [comment]
Thank you for the report!

**Comment by immutability** [comment]
@jameskleeh Sorry to bug you again but I've just tried to upgrade to 1.2.7 and while the issue itself is fixed, it seems to exhibit some odd behavior when a list of includes is used with g:render - that is, if an embedded object property is listed within "includes" it stops working and only renders an empty JSON object i.e. {}

So if you just take the sample project embedded.zip attached in the original issue report, and edit build.gradle to use JSON Views 1.2.7 the test will pass. But if you edit grails-app/views/api/user/show.gson to read:
`json g.render(user, [includes: ['id', 'name', 'mailing', 'physical']])`

instead of just 
`json g.render(user)`

it will fail the test. Everything works if some properties are excluded, but if "includes" is used to only render specific ones, it won't work. I'm not sure if this is a separate issue (and should be reported separately) or if it's expected behavior in this case? Thanks!
