### ISSUE TITLE
JSON is rendering different in WAR deployment vs springboot

### ISSUE THREAD

**Issue by raydawg2000** [grails/grails-views#151]
When in DEV using spring boot the JSON generated from my template is different than when in Production which is deployed via WAR file.

```
model {
    List roles
}

json g.render(roles)
```

In DEV this is my JSON
`[{"label":"Attendee","module":"user"},{"label":"Event Manager","module":"manager"},{"label":"Administrator","module":"admin"}]`

In production this is my JSON
`{"roles":[{"label":"Attendee","module":"user"},{"label":"Event Manager","module":"manager"},{"label":"Administrator","module":"admin"}]}`

It's not app breaking for me as I can just modify my client side to handle the difference, but the inconsistency is odd and not sure if its a bug or not.

**Comment by jameskleeh** [comment]
Please upload an example application with steps to reproduce

**Comment by ilopmar** [comment]
Closing due to lack of feedback
