### ISSUE TITLE
autoEscape not working on "deep" string-like values?

### ISSUE THREAD

**Issue by BardurArantsson** [grails/grails-views#153]
(I suppose this may be more of a question than an issue per se, but...)

I have the following model class:

```groovy
package grails.plugin.markup.view

class A {
    String x
}
```

(I put my class into the `grails.plugin.markup.view` alongside the grails-views specs just for convenience. Same for the spec below.)

I also have the following spec:
```groovy
class MyAutoEscapeSpec extends Specification {

    void "my autoescape spec"() {

        given:
            MarkupViewConfiguration config = new MarkupViewConfiguration()
            config.setEncoding("UTF-8")
            config.setAutoEscape(true)

            MarkupViewTemplateEngine engine = new MarkupViewTemplateEngine(config)

            Template template = engine.createTemplate(
                """|import grails.plugin.markup.view.A
                   |model {
                   |   A a
                   |   String z
                   |}
                   |
                   |A(a.x)
                   |newLine()
                   |B("<>123")
                   |newLine()
                   |C(z)
                   |""".stripMargin())

        when:
            A a = new A([x: "12<>3".toString()])

            Writable output = template.make([a: a, z: "12345<>67"])
            def s = new StringWriter()
            output.writeTo(s)
            def result = s.toString()

        then:
            System.out.println(result.toString())
    }

}
```

which produces the output

```
<A>12<>3</A>
<B><>123</B>
<C>12345&lt;&gt;67</C>
```

However, given that both the 'interpolated' bits of the A and B elements are strings (and autoEscape == true), I would have expected both the A and B bits to also have been escaped.

Is this intentional? I can't seem to find anything about this behavior in the documentation, it just says that string-like values (inherited from CharSequence) shall be escaped.

It certainly seems quite surprising.

(I realize that one could use yield(), but that's quite inconvenient and error-prone in our use case.)

**Comment by jameskleeh** [comment]
Really this is all on the Groovy side. As far as I can tell only the model is `autoEscaped`. If you look at the documentation (http://groovy-lang.org/templating.html#markuptemplate-autoescape) it states: 

> the template configuration provides an option which will automatically escape objects from the **model**

Unfortunately this part of the code is in the hands of Groovy so it take a drastic change in the way markup views are created to change the behavior.

**Comment by BardurArantsson** [comment]
I guess the documentation is kind of ambiguous. I mean "A" is also from the model, so... (Plus, the current behavior is kind of useless or even outright dangerous for those who are unware, especially since autoEscape is on by default.)

Oh, well.

Thanks for the clarification, regardless. I guess we'll have to manually escape everything or transform our objects before sending them off to the views.
