### ISSUE TITLE
Json Custom Converters not available when using g.render method

### ISSUE THREAD

**Issue by sudosandwich3** [grails/grails-views#158]
Given a Custom Converter for myCustomProp, the following works correctly:

```
model {
  MyClass myClass
}
json {
  myCustomProp myClass.myCustomProp
}
```

But when i try to do:
```
model {
  MyClass myClass
}
json g.render(myClass, [includes:['myCustomProp'])
```
or
```
model {
  MyClass myClass
}
json g.render(myClass, [includes:['someOtherProp']) {
  myCustomProp myClass.myCustomProp
}
```
The converter is not applied.  

Looking at the source code it looks like DefaultJsonGenerator is being created without the converters being set by the static block in JsonOutput.

**Comment by jameskleeh** [comment]
@sudosandwich3 Please upload an example project that reproduces the issue

**Comment by jameskleeh** [comment]
So by default the `g` will attempt to process any non simple types in order to support things like includes/excludes/etc. If you want to have it processed directly by json, you should exclude it then output it directly via the customizer closure. 

For example:

```
json g.render(myClass, [excludes: 'duration']) {
  duration myClass.duration
}
```

**Comment by sudosandwich3** [comment]
@jameskleeh 

Documenting this behavior will definitely be helpful, but is there any future enhancement for g.render to use custom converters as well?

**Comment by jameskleeh** [comment]
@sudosandwich3 A configuration value or parameter could be supported to indicate which properties should be passed directly to json. If you would like to work up a PR I think it is something worth exploring.
