### ISSUE TITLE
GenericGroovyTemplateViewResolver can not set order

### ISSUE THREAD

**Issue by ibmsoft** [grails/grails-views#159]
it seems  that GenericGroovyTemplateViewResolver can not set order

then then GenericGroovyTemplateViewResolver always in the last,but i have custom view resolver
want to the last one,how to achieve this

**Comment by ilopmar** [comment]
@ibmsoft Can you please provide a sample project that reproduces this issue?

**Comment by ilopmar** [comment]
Closing due to lack of feedback
