### ISSUE TITLE
JsonViewUnitTest - error when try to add a class to mapping context

### ISSUE THREAD

**Issue by AmaliaMV** [grails/grails-views#166]
I am using the new trait `grails.plugin.json.view.test.JsonViewTest` to test gson view. When I want to add a class to the mappingContext I have an error

```
groovy.lang.MissingMethodException: No signature of method: static com.brinqa.platform.core.model.DataModelViewSpec.grails_views_json_test_JsonViewUnitTest___mappingContext$set() is applicable for argument types: (org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext) values: [org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext@709d86a2]
```

I was debugging and I found some strange. Would it be that the type of `_mappingContext` attribute is wrong? As you can see in https://github.com/grails/grails-views/blob/master/json-testing-support/src/main/groovy/grails/views/json/test/JsonViewUnitTest.groovy#L18, the type is `JsonViewTemplateEngine`, is it possible that the type should be  `MappingContext`?

**Comment by AmaliaMV** [comment]
Oh! you are right!, I wrote wrong the name of the trait. (`grails.views.json.test.JsonViewUnitTest`).

My problem is when I call `getMappingContext().addPersistentEntities(....)`, I have 

```
groovy.lang.MissingMethodException: No signature of method: static com.brinqa.platform.core.model.DataModelViewSpec.grails_views_json_test_JsonViewUnitTest___mappingContext$set() is applicable for argument types: (org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext) values: [org.grails.datastore.mapping.keyvalue.mapping.config.KeyValueMappingContext@709d86a2]
```

I think the problem is that you have this

```
private static JsonViewTemplateEngine _mappingContext

/// ...

MappingContext getMappingContext() {
        if (_mappingContext == null) {

//  here it trys to save a MappingContext into JsonViewTemplateEngine variable

            _mappingContext = applicationContext.getBean('grailsDomainClassMappingContext', MappingContext)  
        }
        _mappingContext
    }
```

**Comment by niravassar** [comment]
Yes, this is a problem and we will fix it.
