### ISSUE TITLE
Absolute view URI should override namespace rule

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-views#169]
Inside a namespaced controller, when I specify a view like so:

```
    static namespace = 'foo'
    def indexAbsolutePath() {
        respond([grailsApplication: grailsApplication, pluginManager: pluginManager], view: '/absolute/index')
    }
```

Expected behavior: The response is rendered from `grails-app/views/absolute/index.gson`.
Actual behavior: The plugin looks for the view in `grails-app/views/foo/absolute/index.gson`. If that view doesn't exist it attempts to render the object by normal convention.

I believe GSP view resolution uses the absolute URI without adding the namespace prefix.

Affected version: 1.2.7

Example project: https://github.com/joemccall86/namespaced-views

**Comment by ilopmar** [comment]
Please note that doing `respond view: '/absolute/index'` is the same as `respond view: 'absolute/index'`, the base directory is `grails-app/views`. Also keep in mind that there is no such thing as "absolute" view URI.
When defining the `namespace` in a controller, as you mentioned, you're changing the search path to first include `grails-app/views/foo` and then, if not found `grails-app/views`

**Comment by joemccall86** [comment]
I've updated the associated test project to illustrate this case as well.
