### ISSUE TITLE
Rendering embedded objects using "includes"

### ISSUE THREAD

**Issue by immutability** [grails/grails-views#171]
This may be related to fixes done in #150 - the embedded objects are now rendered properly, but only unless you use "includes" to explicitly list properties to be rendered - in that case, you'd just get an empty JSON object in place of the expected embedded object. Not sure if this is the expected behavior? It works OK when "excludes" is used to exclude some properties.

The attached test app ([embedded.zip](https://github.com/grails/grails-views/files/2119168/embedded.zip) - Grails 3.1.x, JSON Views 1.2.8) is using a User domain with a simple embedded Address - there are 3 JSON views to render a user - one using plain g.render, another one using "includes" to include only the name and mailing address, and another one using "excludes" to achieve the same goal. There's a unit and integration/functional test - just run grails test-app and the unit test will fail on the "includes" version of the JSON view. I hope I didn't screw up the sample app again. :)

The workaround with an explicit default template for the address under views/address/_address.gson would still work as it did before #150 was fixed in version 1.2.7.

Thanks for all your work on this plugin!

**Comment by smakela** [comment]
Do I understand right that embedded objects has to be explicitly added to "includes" list?
So If I have object Foo which has object Bar as embedded field I have to add that bar to inlcudes list?
