### ISSUE TITLE
Markup Views seem to break Grails Content Negotiation

### ISSUE THREAD

**Issue by matthew-long** [grails/grails-views#180]
I've written a controller that supports XML and JSON responses.
I'm using the Accept header to control which response type gets sent back as described at http://docs.grails.org/latest/guide/theWebLayer.html#contentNegotiation
Using the previous converters mechanism this works as expected.
After switching to use JSON views and Markup Views the Markup view is always rendered regardless of the Accept header.
I'm using Postman to send the request, so Grails shouldn't be ignoring the Accept header.

Created example application at https://github.com/matthew-long/grails-views-resolution
This just adds an application.gml next to the application.gson file.

**Comment by jameskleeh** [comment]
@matthew-long In order to use content negotiation, you must use the `respond` method.

Changing index to the following produces the behavior you expect:

```
    def index() {
        respond([grailsApplication: grailsApplication, pluginManager: pluginManager])
    }
```
