### ISSUE TITLE
Child domain class properties are not rendered. Basic associations are not rendered

### ISSUE THREAD

**Issue by smakela** [grails/grails-views#184]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Start example application (Needs mongodb running on default port)
2. Browse to http://localhost:8080/embedded/index
3. Check the result

### Expected Behaviour

This is normal case in the MongoDB that the data is emebedded instead of making refs to other collections.

Controller should render following json:

`{"cees":[{"code":"c1","name":"c1"},{"code":"c2","name":"c2"}],"bees":[{"code":"c1","name":"c1"},{"code":"c2","name":"c2"},{"code":"b1"}], "data":{"key1":"value1","key2":"value2"}}`

### Actual Behaviour

Controller renders following json:

`{"cees":[{"code":"c1","name":"c1"},{"code":"c2","name":"c2"}],"bees":[{"code":"c1"},{"code":"c2"},{"code":"b1"}]}`

- It does not have the "data" Map
- Instances of C object in the list "bees" do not have "name" attribute

If you look at the database, instances of C in the "bees" list have the "class" attribute, so there is no reason that this object is not rendered as instance of C (instead of B what is now happening).

### Environment Information

- **Operating System**: OSX 10.13.5
- **Grails Version:** 3.3.8
- **JDK Version:** Oracle 1.8.0_72-b15

### Example Application

- https://github.com/smakela/embeddedJson

**Comment by jameskleeh** [comment]
@smakela In any case it should not be a show stopper since you can simply render the object as json manually

**Comment by smakela** [comment]
Ok. Tell me how to do it. I'm listening.

**Comment by jameskleeh** [comment]
@smakela It absolutely is an option. http://views.grails.org/latest

**Comment by smakela** [comment]
@jameskleeh Your are seriously suggesting workaround that I will do template for every domain that we have in our app?

**Comment by smakela** [comment]
@jameskleeh You can just make workaround PR to my repo to make it render expected result.

**Comment by jameskleeh** [comment]
@smakela I wasn't suggesting you to create a template for every domain in your app. I said it wasn't a showstopper because you have an avenue to achieve the result you want. I appreciate the offer to submit a PR to your repo

**Comment by smakela** [comment]
May I will make PR if I find the solution. It was somewhere deeper. I debugged a little but and those Map's are not rendered because they are Associations but not instanceof Emebedded. And mapping context returns the parent class so that is why the attributes of child are not rendered.

**Comment by smakela** [comment]
@jameskleeh Wow! That was fast. Thank you sir!

**Comment by smakela** [comment]
@jameskleeh One little question. If I looked correctly Travis made 1.2.9.BUILD-SNAPSHOT version of this plugin? When can we expect the 1.2.9 version release? Thank you!

**Comment by jameskleeh** [comment]
@smakela Yes you are correct that 1.2.9.BUILD-SNAPSHOT was published. I don't know when 1.2.9 will be released. It depends how long it will take to fix other issues we deem important enough to include in the next release
