### ISSUE TITLE
Issue with tmpl notation on sub collections

### ISSUE THREAD

**Issue by mlentzner** [grails/grails-views#19]
Environment: Grails 3.1.4, Mongo Plugin 5.0.3

Accessing a collection inside an object as part of another collection does not seem to work:

```
model {
    FlexTimeSheet timeSheet
}

json {
    lineItem tmpl.'/lineItem/lineItem'(lineItem: timeSheet.lineItems[0]) //<< this works
    lineItems tmpl.'/lineItem/lineItem'(timeSheet.lineItems) //<<this does not - passes list of nulls to template
    lineItems g.render(template: '/lineItem/lineItem', collection: timeSheet.lineItems, var:'lineItem') //<< this works
}
```

parent `timeSheet` was accessed like this:

```
model {
    Iterable<FlexTimeSheet> timeSheets
}

json tmpl.timeSheet(timeSheets ?: [])
```

Also tested with simply declaring a List of Maps and that did not work either. 

Note: May be related to Mongo Plugin 5.0.3 version.

**Comment by mlentzner** [comment]
Just realized it might be the `tmpl.'/path/template'` notation that is the problem

**Comment by graemerocher** [comment]
I believe this is fixed in 1.0.7 of the plugin, please try:

       compile "org.grails.plugins:views-json:1.0.7"

**Comment by graemerocher** [comment]
Duplicates https://github.com/grails/grails-core/issues/9858 and fixed by https://github.com/grails/grails-views/commit/ba6d98cc8157101d842bc0a3198cd3c2dffc9bef

**Comment by mlentzner** [comment]
Confirmed fixed.

Is there a way to declare the `var` when passing a collection to tmpl?

**Comment by graemerocher** [comment]
@mlentzner  yes, you can use 2 arguments:

`tmpl.'/foo/bar'('myVar', collection)`

**Comment by mlentzner** [comment]
Thanks! Suggest this be added to the documentation.
