### ISSUE TITLE
GrailsDomainClassMappingContext not found

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-views#197]

**Comment by graemerocher** [comment]
This class was deprecated and has been removed

**Comment by sdelamo** [comment]
See: 
https://github.com/grails/grails-views/commit/a9a41909ba39b9dffb034f9feeaf59514da894db

and: 

https://github.com/grails/grails-views/commit/8992d19cf4b5a2072b3e8fc8604f865e2d8cc466
