### ISSUE TITLE
Grails json-views generates JSON with missing comma

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-views#211]
**Simple example:**
https://github.com/rmorrise/demo-parse-error

**Version info:**
```
grailsVersion=3.3.8
gormVersion=6.1.10.RELEASE

compile "org.grails.plugins:views-json:1.2.10"
```

**Steps to reproduce:**
1) Run the demo application
2) Visit the index page

**Expected results:**
```
{"firstItem":"foo","secondItem":{},"thirdItem":"bar"}
```

**Actual results:**
```
{"firstItem":"foo","secondItem":{}"thirdItem":"bar"}
```
Note the missing comma between secondItem and thirdItem.

**Comment by jameskleeh** [comment]
Please verify it also fails with 1.3.0

**Comment by rmorrise** [comment]
@jameskleeh Thanks for the quick reply. Verified it also exists in 1.3.0. (I also updated `compile "org.grails.plugins:views-json-templates:1.3.0"`, which I forgot to do in the demo version.)

**Comment by rmorrise** [comment]
Note that it's possible to work around the issue by creating a view template for the `CustomerContext` class using `generate-views`.

**Comment by dgerbaudo** [comment]
Hello, Is there a workaround for this issue?

**Comment by dgerbaudo** [comment]
Thanks for the fix. Now It works.
