### ISSUE TITLE
"errors" key is not rendered by JSON view

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-views#215]
Assuming to have as model a map containing a key named `"errors"`, I noticed that it is not rendered by JSON view (other keys are included as expected).

Here's the sample code of a controller's action and JSON view.

_DemoController.groovy_

    def index() {
      Map map = [
        error: 1,
        errors: [1,2,3,4],
        obj: [
          stuff: ['a','g'],
          bool: true,
          error: 5, 
          errors: [5,6,7,8]
        ]
      ]

      render view: 'path/json', model: [ map: map ]
    }

_json.gson_

    model {
      Map map
    }
    
    json g.render(map)

Actual result:

    {
      "error": 1,
      "obj": {
        "stuff": [ "a", "g" ],
        "bool": true,
        "error": 5,
        "errors": [ 5, 6, 7, 8 ]
      }
    }

**Comment by puneetbehl** [comment]
Fixed in PR #219
