### ISSUE TITLE
.war archive contains 2 copies of the same compiled JSON views

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-views#216]
I recently updated my Grails app to use JSON views. I noticed that in .war archive compiled files for JSON views are duplicated

**Steps:**
1. download sample project at https://github.com/ilPittiz/Grails-views-demo.
It defines 2 JSON views, at `views/json.gson` and `views/main/json.gson`
2. run `assemble` Gradle task to build .war archive
3. list .war content (e.g. `unzip -l archive.war` on *NIX) or unzip the archive right away (e.g. `unzip archive.war`). You'll find that `.class` files for both views are duplicated, so e.g. when unzipping the archive (without settings for file duplicates management, e.g. `unzip -o`) you'll be prompted to choose what to do with duplicates (override or not single file or all duplicates, rename, etc)

**Environment:**
- Grails 4.0.1
- JSON views plugin 2.0.0.RC2
- JDK 1.8

**Comment by bartoleo** [comment]
I have the same problem with a Grails 3.3.10 application with default json pages
Same issue opened on grails-core issues: https://github.com/grails/grails-core/issues/11429
