### ISSUE TITLE
Support platform filesystem path separator in GenericGroovyTemplateResolver.resolveTemplateName

### ISSUE THREAD

**Issue by alanwilkie-finocomp** [grails/grails-views#232]
Version 2.0.2 of the plugin currently fails some test cases when built on Windows because of differences in the filesystem path separator. The problem also manifests in Grails 4.0.4 which updated to 2.0.2. On Windows, Grails controllers fail to resolve GSON views and either throw an exception, or fall back to a default JSON renderer.

I tracked the problem down to a change that was made in GenericGroovyTemplateResolver.resolveTemplateName that conditionally removes leading path separators. I think the right thing to do is remove the separator if it is either a resource path separator _or_ a filesystem path separator.

I've created PR #231 with the proposed change. I've verified that the change builds correctly on Windows, and also resolves the view resolution problem in Grails 4.0.4.

It would be great to get this fixed on the 2.0.x branch and for it to be included in a Grails 4.0.x release.

**Comment by rsanders-relias** [comment]
I've seen this in a real project.  Both the 2.0.0 and 2.1.0.M1.  It can be seen if inspecting the generated class files; there are 2 underscored between the project name and the file. However the template resolver is looking for class files with a single underscore (as seen by turing logging of views to TRACE), this results in a view not found exception.  This can be seen in the vanilla 'angular' skeleton project with ApplicationController and associated view.

**Comment by andrewcanby-finocomp** [comment]
@puneetbehl I can see this is slated for 2.0.3 release. Do you know when this will be available?

**Comment by puneetbehl** [comment]
I am planning to release 2.0.3 today.
