### ISSUE TITLE
NullPointerException in template inheritance if model variable is null

### ISSUE THREAD

**Issue by gmore** [grails/grails-views#234]
When a field of a Gson view is null, and the view inherits from another template,
a `NullPointerException` occurs.

Example:

__parent.gson_
```
model {
   Foo foo
}
json {
   ...
}
```

_inherited_view.gson_
```
inherits template: "/a_path/parent"
model {
   Foo foo
}
json {
   ...
}
 
```
The culprit is in the class grails.plugin.json.view.JsonViewWritableScript, method prepareParentWritable()

```
private GrailsView prepareParentWritable() {
        parentModel.putAll(binding.variables)
        for(o in binding.variables.values()) {
            parentModel.put(GrailsNameUtils.getPropertyName(o.getClass().getSuperclass().getName()), o)
        }
        ...
```
because in the for loop, the variable o is `null`

**Comment by puneetbehl** [comment]
@gmore PR is welcome!
