### ISSUE TITLE
JsonViewJsonRenderer renders before Interceptor after call and model field is null

### ISSUE THREAD

**Issue by flicken** [grails/grails-views#235]
An Interceptor's `model` field is always `null` when the renderer is `JsonViewJsonRenderer`.   I [posted this on Stackoverflow](https://stackoverflow.com/questions/64087536/grails-json-renderer-not-exposing-model-for-interceptor/) where @jeffbrown confirmed that the `model` should be available, so this seems like a bug.  

Repository with minimal example ([flicken/grails-json-interceptor-missing-model](https://github.com/flicken/grails-json-interceptor-missing-model)) showing problem and a [workaround](https://github.com/flicken/grails-json-interceptor-missing-model/blob/main/src/main/groovy/json/interceptor/missing/model/WorkaroundJsonViewResolver.groovy#L28) that works for my use case.  Happy to help implement a fix that could be merged.

The problem is that `JsonViewJsonRenderer` (which extends `DefaultViewRenderer`) directly calls

```groovy
  view.render(model, request, response)
```

and doesn't to expose a `ModelAndView` instance.

Other renderers e.g. DefaultHtmlRenderer, expose the model via:
```groovy
 applyModel(context, object)
```

**Comment by puneetbehl** [comment]
Thank you @flicken for the detailed information.
