### ISSUE TITLE
New Feature: Support for automatic resource expansion for child associations

### ISSUE THREAD

**Issue by trauts2** [grails/grails-views#25]
I see the includes/excludes parameter, but if we use a custom template to render a JSON view, is there a way in the template to optionally include child content?  I see how this would work if using the automatic domain rendering.  And I see how to include children from a template.  It might be worth adding to the docs an example showing how to use custom templates and implement [resource expansion like Atlassian](https://developer.atlassian.com/confdev/confluence-rest-api/expansions-in-the-rest-api)/google does.

**Comment by graemerocher** [comment]
There is nothing built in right now, the way you would do this though is via `g.render(..)` with `includes` or `excludes`
