### ISSUE TITLE
Mongo id's should be toString()'ed before publishing as JSON

### ISSUE THREAD

**Issue by mlentzner** [grails/grails-views#29]
Currently a call like this:

json {id <MongoDomianObject>.id} results in a full expansion of the id object like this:

`"id":{"class":"org.bson.types.ObjectId","date":"2016-03-15T19:05:47Z","inc":-2076039199,"machine":549728092,"new":false,"time":1458068747000,"timeSecond":1458068747,"timestamp":1458068747}`

Default behavior should be the result of 'toString()' on the id object as only the stringed Id is useful in the context of a REST response.

**Comment by mlentzner** [comment]
public gh repo at mlentzner/grails-issues

Comment: //Grails View issue #29 - default <domain object>.id should simply create string version of id

**Comment by PatrickHuetter** [comment]
Using current 1.1.0.M2 release this problem still exists.
![bildschirmfoto 2016-06-10 um 17 05 14](https://cloud.githubusercontent.com/assets/1142911/15968787/8721f112-2f2d-11e6-8c51-50828e54c4bc.png)

**Comment by graemerocher** [comment]
@PatrickHuetter please provide an example in a new issue
