### ISSUE TITLE
Document Requirement for Servlet API 3.1

### ISSUE THREAD

**Issue by csoete** [grails/grails-views#32]
Was trying to get views working on production server running tomcat 7. Should probably be documented somewhere, upgrading to tomcat 8.0 fixed the issue (application running without views has no problem with tomcat 7 it seems).

> I get the following exception java.lang.NoClassDefFoundError: javax/servlet/http/HttpUpgradeHandler when rendering a GSON view in "production" tomcat 7.0.67 jdk1.8.0_77  Triggered from GenericGroovyTemplateView.groovy line 96 grails version 3.1.4
> https://github.com/grails/grails-views/blob/v1.0.8/core/src/main/groovy/grails/views/mvc/GenericGroovyTemplateView.groovy#L96
> Class HttpUpgradeHandler was added in servlet-api 3.1 and tomcat 7 is 3.0. the conclusion is grails-views requires servlet api 3.1 as a minimum?

**Comment by graemerocher** [comment]
Did you test compiling against Servlet 3.0?
