### ISSUE TITLE
Direct access to underlying Writer

### ISSUE THREAD

**Issue by gregopet** [grails/grails-views#35]
In our app we have several sources of JSON strings that need to be passed verbatim to the client (client side settings and GeoJSON being the most prominent examples). The GeoJSON instances in particular can be large, they are generated by the database and there is often no good reason for the web application to transform them into object graphs before forwarding them to the client.

As they are included as properties of a larger API object we currently have to `JSON.parse()` them and let JSON views serialize them back again, but this seems like a big waste. A version of the `raw()` method from regular views would be useful, but access to the underlying Writer would be even better as some JSON serializers must be given a Writer to work with (a server side GeoJSON producer would work like that, for example).

The api could look like this for example:

	model {
		JsonProducer producer
	}

	json {
		json.withWriter "customJson", { writer -> producer.write(writer) } // Would render a property "customJson" containing the object returned by producer
	}

The code would have to assume a valid JSON object or array had been written to the output.

Is something like this already planned? Would it be an easy thing to add? Would you accept a pull request with such a function?

**Comment by graemerocher** [comment]
the writer is already available using the `out` variable

**Comment by gregopet** [comment]
Oh, so it is.. I didn't see it in the documentation and assumed it won't work.

Thank you, for this information and for all the work you do on Grails :+1:
