### ISSUE TITLE
[Static type checking] - No such property: id for class: java.lang.Object when iterating an association defined as List 

### ISSUE THREAD

**Issue by mangebjl** [grails/grails-views#38]
I get the error described here with Grails 3.1.6 on a windows 7, 64 bit machine.

**Foo class:**

`class Foo {

    String name 

    static hasMany = [bars:Bar]

    static constraints = {
    }
}`

**Bar class:**

`class Bar {

    String name
    Foo foo

    static constraints = {
    }
}`

**Json view for foo (show.gson):**

`model {
    Foo foo
}

json {
    foo g.render(template:"foo", model:[foo:foo])
}`

**_foo.gson template:**

`model {
    Foo foo
}

json {
    name foo.name
    bars foo.bars.collect { it.id }
}`

**But if I change the foo class to use a List instead like this:**

`class Foo {

    String name

    List bars

    static hasMany = [bars:Bar]

    static constraints = {
    }
}`

> [Static type checking] - No such property: id for class: java.lang.Object @ line 13, column 29. bars foo.bars.collect { it.id }

**Comment by graemerocher** [comment]
It should be `List<Bar>`

**Comment by sctse999** [comment]
Can we turn off static type checking in grails view?

**Comment by sctse999** [comment]
Found the way to disable compileStatic in grails view:

application.groovy 
```
grails.views.json.compileStatic = false
```

Would be great if this is also include in grails view doc. Thanks.

**Comment by jameskleeh** [comment]
It is in the documentation.. http://views.grails.org/latest/#_configuration

**Comment by sctse999** [comment]
@jameskleeh , you are right. Thanks for pointing out.
