### ISSUE TITLE
Transactions and conventions problems

### ISSUE THREAD

**Issue by volnei** [grails/grails-views#4]
I'm just starting to use this plugin and I'm frustrated by two things:

First, the convention for entitiy gson file (Book -> /views/book/_book.gson) is confused, cause sometimes we need to have a controller named BookController and their own views (by Grails convention /views/book folder) causing a dual function for /book folder. Maybe convention be more clear if it was /views/model/_book.

Second topic is about using RestfulController, because of nature of transactions when we save() an object, for example, your corresponding view was rendered but if we need a lazy loading we can't get it, even if you uses object.refresh() or re-read the object, cause transaction only flush after gson is rendered. When using html this is bypassed because of redirect.

Thanks

**Comment by graemerocher** [comment]
1) I'm failing to see how this is an issue, the `_book.gson` is a template not a view, so I don't see where the conflict emerges fro

2) If you need to render an item that is loaded from the database then use an eager query which will perform better anyway

**Comment by volnei** [comment]
Graeme,

1) It's not an issue, but think in an hybrid app (rest+html) with this folder organization, also think that templates does not support controller namespaces and will see how confuse it could be. Also as you said, gson it's not a view and I think that the /grails-app/views folder it's not a good place to put them. 

2) You're right, sorry about that.

**Comment by graemerocher** [comment]
GSON are not views? where did I say they are not? They are and are absolutely designed as such. Also I am failing to see how a hybrid app would have a problem, since the extensions (`.gson` and `.gsp` ) do not conflict. Either way I'm failing to see any identified bug in this discussion.

**Comment by volnei** [comment]
Ok, there's nothing to discuss here.
