### ISSUE TITLE
Locale switching Issue (grails 3.1.4, views 1.0.8)

### ISSUE THREAD

**Issue by csoete** [grails/grails-views#40]
Opening up a browser with locale set to one language and switching to a different language will result in some kind of loop/memory problem. (The attempted view being rendered is a gson view with a simple collection of domain instances.)

The issue is somehow related to `ResolvableGroovyTemplateEngine.resolveTemplate`.

The error presented at console level is:
```
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3210)
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
```

The following visualvm screenshots helped me find the relevant code:

![memusageresolvetemplate](https://cloud.githubusercontent.com/assets/13430361/15247451/9dc8b5d8-1914-11e6-86cb-631a01fdd5fc.png)
![resolvetemplate](https://cloud.githubusercontent.com/assets/13430361/15247450/9dc87c62-1914-11e6-8a1c-9f9ae2cde6d3.png)

Using version 1.0.9 did not resolve the issue.

**Comment by csoete** [comment]
Workaround force locale to US (resources.groovy): 
```
beans = {
    
    localeResolver(org.springframework.web.servlet.i18n.SessionLocaleResolver) {
        defaultLocale = new Locale("en","US")
        java.util.Locale.setDefault(defaultLocale)
    }
}
```

**Comment by graemerocher** [comment]
Duplicates #34

**Comment by jpguptaito2** [comment]
how to set Locale in gson views

**Comment by jpguptaito2** [comment]
json{
 name g.message(code:"course.title",locale:"FI")
}
Why its  always  fetching "code.title"  from default messages.properties but not from messages_fi.properties ?  Please .......
