### ISSUE TITLE
problems displaying all fields in a org.springframework.data.solr.core.query.result.Highlightpage

### ISSUE THREAD

**Issue by walshe** [grails/grails-views#41]
Hi,

Im using grails 3.1.5 with the angular profile.

Im using Spring Data Solr and Spring Data rest in the project as theres a lot of Solr querying.

Anyway theres one part in the project where im using SolrTemplate to do a solr query and then return the results in json to the angular service, I found that it works fine if I do this in a spring mvc style @Restful controller in my groovy/src directory

    @RequestMapping(value =  "/", method = [RequestMethod.GET])
    def search(SearchCommand searchCommand, Pageable pageable, HttpSession httpSession) {

    ...
    ....
        return searchService.search(enhancedSearchCommand, enhancedPageRequest)

    }

and in the service..

    HighlightPage search(EnhancedSearchCommand searchCommand, Pageable pageable){
    ...
    ..
        return solrTemplate.queryForHighlightPage(highlightQuery, CourseGuide)

    }

i.e. it returns json with all the 'meta-data' fields from the highlightpage obj, numelements, facetfields etc etc

However if try to do this with a regular grails controller and new grails views there are a bunch of the fields missing in the json that are otherwise getting returned by the @RestController.. basically all this meta data is missing:

      "facetResultPages": [
    
  ],
  "facetQueryResult": {
    "content": [
      
    ],
    "totalPages": 1,
    "totalElements": 0,
    "last": true,
    "size": 0,
    "number": 0,
    "sort": null,
    "numberOfElements": 0,
    "first": true
  },
  "highlighted": [
    {

is there some setting I need to change somewhere?

thanks

**Comment by graemerocher** [comment]
This is written more like a question, please use Slack for questions. I wasn't even aware the plugin was useable from a regular Spring controller, either way provide an example that reproduces the issue.

**Comment by walshe** [comment]
I wasn't aware of the Slack forum, in fact not sure what best forum is at all these days 


re above, the spring controller is not using any plugin its just returning the highlighpage (in json) as it normally would and does so correctly. My issue is trying to get a regular grails controller to do the same

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
