### ISSUE TITLE
Accept-Version Content Negotiation not working JSON Views.

### ISSUE THREAD

**Issue by rohitpal99** [grails/grails-views#43]
I created new Grails 3.1.4 application
Installed JSON view as per http://views.grails.org/latest
Created controller UserController
Created index_v1.gson and index.gson in /view/user/

Checked http://localhost:8080/user. Response JSON always is from index.gson even when sending header "accept-version": "v1"

Using Postman
Plugin: views version 1.0.9

**Comment by graemerocher** [comment]
Tested this out and it works fine for me. Will need an example that reproduces the problem uploaded to github

**Comment by rohitpal99** [comment]
Tried with complete new project and still couldn't get it working.
https://github.com/rohitpal99/grails-rest-version-test

1. http://localhost:8080/user
2. http://localhost:8080/user with Accept-Version: "1.0"

always produces same json response

```
{
  "users": [
    {
      "firstName": "Bon",
      "lastName": "Jovi"
    },
    {
      "firstName": "Frank",
      "lastName": "Miller"
    }
  ],
  "count": 2,
  "version": "v2"
}
```

Please pin out issues with code if any. Thanks.

**Comment by graemerocher** [comment]
There was a bug which I fixed, but you need to name your templates after your version, so in the example it should be `index_1.0.gson`
