### ISSUE TITLE
'model' cannot be outputted as a key in JSON

### ISSUE THREAD

**Issue by bockhost** [grails/grails-views#45]
```
json {
    make 'Honda'
    model 'Civic'
}

```

outputs:

`{"make":"Honda"}` instead of `{"make":"Honda","model":"Civic"}`.

**Comment by jeffbrown** [comment]
If you quote `model` as `'model'`, does it work?

**Comment by jeffbrown** [comment]
Hmm... I think that probably won't work.  I think I know why that is.

**Comment by jeffbrown** [comment]
This is a hackus majoris but just to get it functioning for now while we investigate, you should be able to get away with something like this...

    json {
        make 'Honda'
        delegate.invokeMethod 'model', ['Civic'] as Object[]
    }

**Comment by bockhost** [comment]
That hackus majoris works great. Thanks!

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-views/commit/75571c3ad46091ba6dfe72e219a570d2bdb103a7
