### ISSUE TITLE
Json views fails to render json, if one of the key name is 'json'

### ISSUE THREAD

**Issue by snimavat** [grails/grails-views#465]
We have Domains, with a property name `json` which is a type Map and mapped to mysql `json` type column

Json views will fail to render if we do

```
json {
   id domain.id
   name domain.name
   json domain.json
}
```

**Comment by snimavat** [comment]
Workaround 

Explicitely call

```
json {
   id domain.id
   name domain.name
   call 'json', domain.json
}

```

This will call the `call` method on `StreamingJsonBuilder.StreamingJsonDelegate` and it would work fine.

**Comment by puneetbehl** [comment]
Thank you for reporting this issue. I think we should update the documentation accordingly.
