### ISSUE TITLE
Using g.link in JSON View is creating absolute URLs in 1.0.11

### ISSUE THREAD

**Issue by StevenToth** [grails/grails-views#48]
I recently upgraded to 1.0.11 of JSON views and using g.link from within the .gson file is now generating absolute URLs.  Grails version is 3.1.6.

    package mypck

    model {
        com.mycomp.Response<Map> response
    }

    json {
        urls {
            save g.link(controller: 'myCont', action: 'saveRec')
        }
    }

Passing 'absolute:false' on the g.link call works around the issue.  However, the default for g.link is relative URLs and therefore we shouldn't have to change every g.link call to use 'absolute:false'.

**Comment by graemerocher** [comment]
I'm struggling to think why in a JSON response relative URLs would be a sensible default.

**Comment by graemerocher** [comment]
Allows this to be configurable for 1.1.0 https://github.com/grails/grails-views/commit/4395330301258570daee1e3972bcbdadeb74d353
