### ISSUE TITLE
Ability to add HAL to default domain class rendering

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-views#5]
`hal.links(object)` works fine when you're including other keys in your JSON view, but it would be nice if it could also work with the default rendering in the same way that you can add additional keys to it. 

For example (in template customerStore/_customerStore.json) :
```
model {
    CustomerStore customerStore
}

json g.render(customerStore) {
    hal.links(customerStore)
}
```

**Comment by graemerocher** [comment]
This is fixed in 1.0.2. You can now do:

       json hal.render(customerStore)

Which will also render the links
