### ISSUE TITLE
Marshaller for objects with a property of class Map

### ISSUE THREAD

**Issue by jromero-onclick** [grails/grails-views#50]
I have this domain:

```java
class Activity implements Comparable<Activity> {

    static constraints = {
        name(blank: false, unique: ['activityLevel3'])
        description(blank: true, maxSize: 500)
        activityLevel3(nullable: false)
        position(nullable: false)
    }

    String name
    String description
    ActivityLevel3 activityLevel3
    Integer position
    Map attributes

    static belongsTo = [activityLevel3: ActivityLevel3]
    static hasMany = [attributes: ActivityAttribute]

    int compareTo(Activity obj) {
        position.compareTo(obj.position)
    }
}
```

And a rest controller for it:

```java
class ActivityController extends RestfulController {
    static responseFormats = ['json']

    ActivityController() {
        super(Activity)
    }
}
```

When I try to get the list (/activity) or to show an activity (/activity/show/1) I get this error:

{"id":1,"activityLevel3":{"id":1},"attributes":
....
<h1>Error 500: Internal Server Error</h1>
                <dl class="error-details">
                    <dt>URI</dt>
                    <dd>/activity/show/1</dd>
                    <dt>Class</dt>
                    <dd>org.grails.web.json.JSONException</dd>
                    <dt>Message</dt>
                    <dd>null</dd>
                    <dt>Caused by</dt>
                    <dd>Misplaced key: expected mode of KEY but was OBJECT</dd>
                </dl>

**Comment by jromero-onclick** [comment]
More info about the example:

ActivityAttribute domain
```java
class ActivityAttribute {

    static constraints = {
        activity(nullable: false, unique: ['attribute'])
        attribute(nullable: false)
        value(nullable: true)
    }

    Activity activity
    Attribute attribute
    String value
}
```

Attribute domain
```java
class Attribute {

    static constraints = {
        code(blank: false, unique: true)
        name(blank: false, unique: true)
        importLabelColumn(blank: false)
        attributeType(nullable: false)
    }

    String code
    String name
    String importLabelColumn
    AttributeType attributeType
}
```

AttributeType enum
```java
public enum AttributeType implements org.springframework.context.MessageSourceResolvable {
    STRING, INTEGER, MONEY, DOUBLE, LIST

    static transients = ["codes", "arguments", "defaultMessage"]
    Object[] getArguments() { [] as Object[] }

    String[] getCodes() {
        ["${getClass().name}.${name()}"] as String[]
    }

    String getDefaultMessage() { name() }
}
```

**Comment by graemerocher** [comment]
This is a bug in Grails core's JSON renderer infrastructure not in the JSON views plugin since the exception `org.grails.web.json.JSONException` is never thrown by the JSON views plugin. Have you tried generating views for your `ActivityController`?

**Comment by jromero-onclick** [comment]
ActivityController is a restful controller. How I have to generate views for it?

**Comment by graemerocher** [comment]
run `generate-views`
