### ISSUE TITLE
JSON rendering in 1.1.0.M1 and 2 not equal to 1.0.12 

### ISSUE THREAD

**Issue by PatrickHuetter** [grails/grails-views#52]
Using the newest version (1.1.0.M2) or milestone 1 the json output isn't consistent and excludes are only working partly. They get inherited while rendering a single object. If you render an array of objects, the excludes aren't working anymore and everything gets rendered. Version 1.0.12 of the plugin renders everything correctly.

**Comment by graemerocher** [comment]
not enough information here. Please upload an example that reproduces the issue
