### ISSUE TITLE
GSON views for springSecurity User domain:  endless while loop (v1.0.9)

### ISSUE THREAD

**Issue by dularion** [grails/grails-views#53]
So we are experiencing this crazy bug. All our gson views work perfectly well and we are super happy with this tool. But now we ran into the issue that the application uses 100% CPU as soon as at least 2 users try to access a gson-view that renders the springSecurityCore User domain object. so something as simple as g.render(user) in our show.gson, accessed from two different login session, will require us to kill the application and restart. Now keep in mind: accessing any other gson referencing any other domain works perfectly well. Also, accessing our user related gsons from one single login session works well too. the issue occurs when 2 sessions access any user related gson endpoint. 

what we found out is that the culprit seems to be a while loop that gets called over and over and over, the following: `/views-core-1.0.9-sources.jar!/grails/views/ResolvableGroovyTemplateEngine.groovy:261`

it seems like the qualifierQueue().peekLast() always contains something. in those cases, `
qualifierQueue.removeLast()` in line 267 doesnt remove anything or never gets called. Debugging this with only one login session works, however - the qualifierQueue is emptied as desired. 

We will try upgrading to 1.0.12 and see if the problem persists. but until then, I thought I should let you know and get your input.

Thanks!

**Comment by graemerocher** [comment]
Thanks for the report, if you can provide an example with steps to reproduce that would be good.

**Comment by dularion** [comment]
we are using grails v3.1.6 and org.grails.plugins:spring-security-core:3.0.3, and views-core-1.0.9. 
I will be supplying an example project shortly (if we can reproduce it there)

**Comment by dularion** [comment]
ah nvm! its fixed in 1.0.12!
