### ISSUE TITLE
List<String> in Domain wont render in JSON view - causes NullPointerException

### ISSUE THREAD

**Issue by kyranlange** [grails/grails-views#54]
If a domain object contains a `List<String>`, when building up the JSON for the instance to display in a JSON view a NullPointerException is thrown.

The NullPointerException is being thrown on line 337 of DefaultGrailsJsonViewHelper.
`def propertyType = ass.associatedEntity.javaClass`
as `ass.associatedEntity` is null. 

This can be tested by adding a `List<String>` to Team in the functional-tests - see [attached patch](https://github.com/grails/grails-views/files/334258/liststringassociation.patch.txt).

Stack trace is:

> Caused by: grails.views.ViewRenderException: Error rendering view: null
> 	at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:33)
> 	at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(GenericGroovyTemplateView.groovy:65)
> 	at grails.views.mvc.renderer.DefaultViewRenderer.render(DefaultViewRenderer.groovy:94)
> 	at grails.artefact.controller.RestResponder$Trait$Helper.internalRespond(RestResponder.groovy:188)
> 	at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy:98)
> 	at functional.tests.TeamController.show(TeamController.groovy:15)
> 	... 3 common frames omitted
> Caused by: java.lang.NullPointerException: null
> 	at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.process(DefaultGrailsJsonViewHelper.groovy:337)
> 	at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper$_render_closure1.doCall(DefaultGrailsJsonViewHelper.groovy:116)
> 	at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:691)
> 	at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:683)
> 	at grails.plugin.json.builder.StreamingJsonBuilder.call(StreamingJsonBuilder.java:199)
> 	at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.render(DefaultGrailsJsonViewHelper.groovy:110)
> 	at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.render(DefaultGrailsJsonViewHelper.groovy:66)
> 	at _info_app_name__team__team_gson.run(_info_app_name__team__team_gson:7)
> 	at grails.plugin.json.view.JsonViewTemplate.doWrite(JsonViewTemplate.groovy:32)
> 	at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:30)
> 	... 8 common frames omitted

**Comment by graemerocher** [comment]
This is already fixed, see tests https://github.com/grails/grails-views/commit/053bc4b9ce70a923d86d326542cb303311a318f0
