### ISSUE TITLE
Deep rendering not consistent with documentation

### ISSUE THREAD

**Issue by bysouleater** [grails/grails-views#58]
As per documentation:

Typically the g.render(..) method will only render objects one level deep. In other words if you have a domain class such as:

```
class Book {
    String title
    Author author
}
```
The resulting output will be something like:
```
{"id":1,"title":"The Stand","author":{id:1}}
```

I've tried in v.1.0.12 and 1.1.0.RC1 and in both cases the result is not what the documentation says. It's actually looking for the author (as a separated query to the database) and including it to the final JSON.

```
import grails.rest.*

@Resource(readOnly = false, formats = ['json', 'xml'])
class Destination {

    String name
    String permalink

    DestinationType type
}
```
```
import grails.rest.*

@Resource(readOnly = false, formats = ['json', 'xml'])
class DestinationType {

    String name
    String permalink

}
```
```
import grails.rest.*
import grails.converters.*

class DestinationController extends RestfulController {
    static responseFormats = ['json', 'xml']
    DestinationController() {
        super(Destination)
    }
}
```
created "grails-app/views/destination/show.gson" file with following content:
```
model {
    Destination destination
}

json g.render(destination)
```
And the resulting JSON is always like this:
```
{
    id: 1,
    name: "Barcelona",
    permalink: "barcelona",
    type: {
        id: 1,
        name: "City",
        permalink: "city"
    }
}
```

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-views/commit/1b2042ee60da9ba1840000f24d90a4af5688f922
