### ISSUE TITLE
Open Test Issues for Grails 7 (grails-views 4.0.x)

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-views#582]
Current Issues:

The interface XXX cannot be implemented more than once with different arguments.  

`implements ContainerRenderer<C, T>` was causing Render<T> to be implement more than once.  It is currently removed from class AbstractJsonViewContainerRenderer<C,T>

- https://github.com/grails/grails-views/pull/581/files#diff-b2646b6110b34798952582e9a501678112c0ed5d810ac556902857099652a31e

Domain Inheritance (commented for now):

- https://github.com/grails/grails-views/pull/581/files#diff-772c74b6220f27b5c33ecf692a2d3cfa2a58522552f3b6cda2459cd28c988fec
- https://github.com/grails/grails-views/pull/581/files#diff-bf15eb842428b308b40a0f307701e937a17196d59e26a6da7d6ab2da09a15641

**Comment by matrei** [comment]
#589

**Comment by jdaugherty** [comment]
Since https://github.com/grails/grails-views/issues/597 was opened, I'm closing this ticket based on the Pull Request

**Comment by jamesfredley** [comment]
I will create another PR to put the following back

The interface XXX cannot be implemented more than once with different arguments.

implements ContainerRenderer<C, T> was causing Render to be implement more than once. It is currently removed from class AbstractJsonViewContainerRenderer<C,T>

https://github.com/grails/grails-views/pull/581/files#diff-b2646b6110b34798952582e9a501678112c0ed5d810ac556902857099652a31e

**Comment by jamesfredley** [comment]
The interface XXX cannot be implemented more than once with different arguments.

implements ContainerRenderer<C, T> was causing Render to be implement more than once. It is currently removed from class AbstractJsonViewContainerRenderer<C,T>

addressed by: https://github.com/apache/grails-core/pull/15234
