### ISSUE TITLE
Grails 7: grails-views: Failed to apply plugin 'org.grails.plugins.views-json'

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-views#587]
org.grails.plugins:views-json:4.0.0-SNAPSHOT

`apply plugin: "org.grails.plugins.views-json"`

```
A problem occurred evaluating root project 'testing-support'.
> Failed to apply plugin 'org.grails.plugins.views-json'.
   > Could not create task ':examples-demo33:compileGsonViews'.
      > Could not create task of type 'JsonViewCompilerTask'.
         > grails.views.gradle.AbstractGroovyTemplateCompileTask: method 'void <init>()' not found
```

**Comment by jamesfredley** [comment]
All that is required to get views-json to render .gson views is:

```
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:7.0.0-SNAPSHOT"
    }
}

apply plugin: "org.grails.grails-web"

dependencies {
    // other normal dependencies
    implementation "org.grails.plugins:views-json:4.0.0-SNAPSHOT"
}
```

`apply plugin: "org.grails.plugins.views-json"` is not required

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-functional-tests/blob/7.0.x/issue-views-182/build.gradle is a good sample project.

`classpath "org.grails.plugins:views-gradle:$viewsVersion"` is not required for gson views to render

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-functional-tests/pull/251

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-testing-support/pull/438

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-async/pull/151

**Comment by james-criscuolo** [comment]
@jamesfredley I posted on the PR, but is there any chance this gets backported to 3.2.x? Gradle 8 support was brought to the recent 6.2 release of grails-core, and in attempting that update I run into this issue.

**Comment by jamesfredley** [comment]
@james-criscuolo possibly, but the bigger issue will be grail-gradle-plugin which has had numerous Gradle 8 changes in the 7.0.x branch.  There have also been Gradle 8 changes in the Grails 7 branches for a few other modules.  

https://github.com/grails/grails-gradle-plugin/pulls?q=is%3Apr+is%3Aclosed+gradle

**Comment by james-criscuolo** [comment]
Understood, yea it would definitely be a concerted effort to bring Gradle 8 support to the existing releases. Seems like it's probably a bit heavy, thank you for the fast response!
