### ISSUE TITLE
Support for global rendering of generic types

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-views#60]
Examples:
1. byte[]
2. Any enum

Essentially anything `JSON.registerObjectMarshaller` supported should also be available to do with json views whether you are using it in the context of a Grails plugin or application.

In this case there should also be a notion of priority so specific enums could be rendered differently, for example.

**Comment by victor-rds** [comment]
Is this the case for some `java.time` classes like `LocalDate` and `LocalDateTime`?
With marshallers it was easy to go back and forth with to string formats and parsing.
I've tried `compileViews` approach with no success can't convert to simple value only to JSON object

**Comment by jameskleeh** [comment]
Supported in 1.2 with converters
