### ISSUE TITLE
Grails doesn't use my gson template while rendering a list of instances

### ISSUE THREAD

**Issue by PatrickHuetter** [grails/grails-views#63]
I'm using grails 3.1.9 (rest-api profile) with views-json:1.1.0.RC1 for building a restful api.
I've some problem which i can't reproduce in a new, clean grails environment so that's the cause i can't provide a test project.

My gson template looks like:
```
model {
	SomeJob someJob
}

json {
	id someJob.id.toString() // because i want a simple objectId-string
}
```
**Expected** response GET /SomeJob :
```
[{
      "id": "sdsfsdfsdfsf"
}]
```

**Real** Response GET /SomeJob (not correct) :
```
[{
      "id": "sdsfsdfsdfsf"
      "attr1": "someAttribute"
      "attr2": "someOtherAttribute"
}]
```

**Real** Response GET /SomeJob/sdsfsdfsdfsf (correct like in the template gson):
```
{
      "id": "sdsfsdfsdfsf"
}
```

Calling GET /SomeJob results in an json array ob someJob instances with ALL attributes. But there should only be the id for each instance. Calling GET /SomeJob/{id} results in a single instance of SomeJob with the correct json like described in the template. So only an object with an id gets showed.

Why isn't grails using my gson template for the list rendering? I can't figure it out. I'm using grails RestfulController.

/UPDATE/ I found a workaround to customize the json response in the documentation which is working for me by customizing the default renderer via resources.groovy. Now i'm able to include and exclude properties/attributes from rendering but it still would be fine to know why the templates aren't working for collections because there are cases where templates are important.
```
someJobRenderer(JsonRenderer, SomeJob) {
        excludes = ['attr1']
}
```

/UPDATE2/ It seems to be related to the domain class. Using the "User" domain class generated by the spring security plugin with gson views works fine, also for the list action (Iterable). I already removed everything except 2 String attributes and the ObjectId from my domainclass but it's not working with that domain class / resource. I also renamed the domain class to test wether it depends on camel case names or not but it had no effect. 

/UPDATE3/ I got it! The problem occurs everytime you use namespaced controllers and urls. After adding a namespace to a restfulcontroller the list/index gson won't get recognized. If i remove the following, it works, so that seems to be a bug.
`static namespace = 'v1'`

**Comment by PatrickHuetter** [comment]
@graemerocher I think it's a bug and i can reproduce it now. Please have a look at UPDATE3 in my post before this.

**Comment by gpottepalem** [comment]
I experience the same problem. I am using grails 3.1.6 (rest-api profile) and views plugin: 1.0.9.
I even tried 1.1.0.RC1.

**Comment by jcolombo1** [comment]
Apparently there is convension for property name. Should be xxxxList like in this example in file index.gson (responds a book list):

model {
  Iterable<Book>   bookList
}
json {
    list tmpl.book(bookList)
}

Notes that here is calling to template _book.gson.If you use another name other than bookList does not work! 
I dont know why but I checked.

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-views/commit/1b2042ee60da9ba1840000f24d90a4af5688f922

**Comment by Vigneshwaran22** [comment]
is it possible to use dynamic finder in gson view.

**Comment by graemerocher** [comment]
Yes but that would not be a good idea

**Comment by Vigneshwaran22** [comment]
okay , i need to get count for each item in list ,is there any other way ?

**Comment by graemerocher** [comment]
perform the logic in a controller or service and pass the information to the view via the model

**Comment by Vigneshwaran22** [comment]
Okay , @graemerocher may i know how to use dynamic finders in gson view , just for my knowledge
