### ISSUE TITLE
Documentation: Templates Path

### ISSUE THREAD

**Issue by victor-rds** [grails/grails-views#65]
Hi,

Please add the `templatePath` and  `prettyPrint` configurations in documentation.

My project has a initial of 20 templates but also GSP pages the `grails-app/views` was mess with one folder per template, with no examples of templates in a sub-directory, and as far I can tell the template scan isn't recursive.

Adding the `templatesPath: grails-app/views/api` solved all my problems, now the scan worked and my views folder less clustered .
But maybe adding support for recursive scan could be better solution, keep in mind the paths are for source code organization only

**Comment by jameskleeh** [comment]
This is documented, albeit not very clear. I added a sentence about the GenericViewConfiguration
