### ISSUE TITLE
Discrepancy between docs and plugin, jsonTemplateEngine bean not present.

### ISSUE THREAD

**Issue by budjb** [grails/grails-views#68]
The [documentation](http://views.grails.org/latest/#_the_jsontemplateengine) states that the plugin registers a bean named `jsonTemplateEngine` with the type `JsonViewTemplateEngine`. I could not get this bean to inject properly in my application, so I dug into the plugin source. I did not find anywhere in the plugin where this bean is registered, which would explain why my application could not find it.

Having this bean available would be useful, but the documentation should at least be correct if there are no plans to add it.

**Comment by budjb** [comment]
👍 thanks!

**Comment by yoann-trouillet** [comment]
thanks
