### ISSUE TITLE
JSON API: Missing methods in JsonApiViewHelper

### ISSUE THREAD

**Issue by brianjohnsen** [grails/grails-views#72]
The `grails.plugin.json.view.api.HalViewHelper` contains a lot of methods but `grails.plugin.json.view.api.JsonApiViewHelper` only contains the one `render` method.

Especially the additional `render` methods would be nice.

**Comment by graemerocher** [comment]
The json-api implementation is a work in progress and not production ready yet...it is not documented yet either. When it is is ready it will be documented and announced.

**Comment by brianjohnsen** [comment]
Of course. I've merely been tasked to exercise it.

**Comment by graemerocher** [comment]
Ah gotcha, my mistake.. keep on exercising! ;-)

**Comment by brianjohnsen** [comment]
Exactly what the doctor ordered :-)

**Comment by ColinHarrington** [comment]
@brianjohnsen The `JsonOutput.JsonWritable render(Object object, Map arguments)` method is being added to influence the rendering.  How do you imagine the other methods being used?

**Comment by brianjohnsen** [comment]
@ColinHarrington I haven't examined the other. I'm mostly interested in the ´JsonOutput.JsonWritable render(Object object, Map arguments)´ method. 
Especially with regards to #74 .

**Comment by ColinHarrington** [comment]
We have added extra methods & support for include/exclude
