### ISSUE TITLE
JSON API: DefaultJsonApiIdGenerator fails if associations are null

### ISSUE THREAD

**Issue by brianjohnsen** [grails/grails-views#73]
If an entity contains empty associations the `grails.plugin.json.view.api.jsonapi.DefaultJsonApiIdGenerator#generateId` method throws an NPE.

This can of course be mitigated by implementing an instance of `grails.plugin.json.view.api.jsonapi.JsonApiIdGenerator` but default should be able to handle it.

**Comment by brianjohnsen** [comment]
Ping @jarl-dk

**Comment by ColinHarrington** [comment]
This should be fixed with e5515ae04653f880afcc876bd330e7e22ba4b173
