### ISSUE TITLE
JSON API: JsonApiViewHelper#render only works with domain objects

### ISSUE THREAD

**Issue by brianjohnsen** [grails/grails-views#74]
The `grails.plugin.json.view.api.JsonApiViewHelper#render` method, aka. the `jsonapi.render()` in gson, only works with domain objects.

It would be nice if one could pass ordinary POGO's.

**Comment by brianjohnsen** [comment]
Ping @jarl-dk

**Comment by ColinHarrington** [comment]
The plan is to get json-api support working with Persistent Entities first and then look at supporting POGOs.

**Comment by brianjohnsen** [comment]
In order to use the `jsonapi` we need either this or #72 (se my answer to your comment). 

In our situation we need this one more, as our domain model significantly differs from the exposed API model.

**Comment by jameskleeh** [comment]
Closing this as there is no current plan to support POGOs with jsonapi
