### ISSUE TITLE
JSON values are not being quoted properly

### ISSUE THREAD

**Issue by brianjohnsen** [grails/grails-views#75]
In a gson view json values are not being quoted properly.

This gson:
```
model {
    String value = 'abc'
}

json {
    example1 "abc"
    example2 "${value}"
    example3 "$value"
    example4 "$value".toString()
}
```

Will render this json:
`{"example1":"abc","example2":abc,"example3":abc,"example4":"abc"}`

Which lacks quotes around the values of example2 and example3.

**Comment by ColinHarrington** [comment]
@graemerocher Good test.  Is this considered fixed now?

**Comment by graemerocher** [comment]
Yes
