### ISSUE TITLE
json view with Polymorphic query

### ISSUE THREAD

**Issue by rkimaoui** [grails/grails-views#76]
Hello there,

First of all, thank you for this great work.
How does json view works with Polymorphic queries ?
I can't make it work. I have same example as in the gorm docs (5.3.2. Polymorphic Queries).
I want to list() method on the Content super class will return all subclasses json views of Content.

Thanks in advance.
Reda

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)

**Comment by rkimaoui** [comment]
It seems like a bug for me:
Here are the details:

```groovy
    class Content {
     String text
    }

    class BlogEntry extends Content {
        URL url
    }

    class Book extends Content {
        String ISBN
    }
```

And my contentController :

```groovy
class ContentController extends RestfulController<Content> {
  
        static responseFormats = ['json', 'xml']
    
        ContentController() {
            super(Content)
        }
    
        def index(Integer max) {
            println '*CONTENT:INDEX*'
            def contents= Content.findAll()
            respond contents 
        }
    }
```

And my views:

```groovy   
// /content/index.gson
    model {
        Iterable<Content> contentList
    }
    
    json tmpl.content(contentList ?: [])

    // /content/_content.gson
    model {
        Content content
    }
    
    json g.render(content)
```

I get an empty result from my controller.
i'm using grails 3.2.0.RC2 with views-json:1.1.0.RC3

I should get all subclasses json views of Content class.

**Comment by rkimaoui** [comment]
@graemerocher do you think it's a bug in grails views ?
See my example above.

Thanks in advance.

**Comment by bioform** [comment]
It is a bug
I don't know why they don't want to fix it....

**Comment by jameskleeh** [comment]
@bioform If you're experiencing a bug, file an issue at https://github.com/grails/grails-views with an example project.
