### ISSUE TITLE
Marshaller curiosity

### ISSUE THREAD

**Issue by ilya-gory** [grails/grails-views#77]
Hello! I believe that this issue is related to closed #29.
Using grails 3.2.0 and org.grails.plugins:views-gradle:1.1.0

There are some domain classes with reference
```groovy
class Book {
  ObjectId id
  String title
  Author author
}
class Author {
  ObjectId id
  String firstName
  String lastName
}
```

## Case 1
(no marshaller no views)

Rendering classes by default: there are no views in view/book etc.

```json
{
  "id": {"class":"org.bson.types.ObjectId","counter":8513725,"date":"2016-09-29T06:30:20Z","machineIdentifier":6240881,"processIdentifier":25430,"time":1475130620000,"timeSecond":1475130620,"timestamp":1475130620},
  "title": "Book of Ra",
  "author": { "id":"57ec12ca5f3a7134d00631b5" }
}
```
Referenced id rendered as String (needed), self id rendered as Object (curiously)

## Case 2
(using marshaller, no views)

I have registered marshaller for `org.bson.types.ObjectId` in `Bootstrap.groovy`
```groovy
	def init = { servletContext ->
		JSON.registerObjectMarshaller(ObjectId) {
			return it?.toString()
		}
	}
```
All fields with type `org.bson.types.ObjectId` rendered as strings (needed).
And result seems to be OK, __unless___ I created custom `book/_book.gson`

## Case 3
(using views)

All fields with type `org.bson.types.ObjectId` are rendering as Objects not Strings. And no matter if I'm using marshaller or not.

**Comment by jameskleeh** [comment]
@ilya-gory Can you provide an example application with steps to reproduce? Seems like there are multiple issues you are reporting here

**Comment by ilya-gory** [comment]
@jameskleeh hmm. cannot reproduce on grails 3.2.0 and gradle 3.1. looks like this already fixed
