### ISSUE TITLE
ContentType always comes back as `application/json` instead of the json derivative requested

### ISSUE THREAD

**Issue by ColinHarrington** [grails/grails-views#79]
**Given:** I have the jsonapi formats setup.
```yml
grails:
    mime:
        types: ...
          jsonapi:
            - application/vnd.api+json
```
**When:** sending an `Accept` header of `applicaiton/vnd.api+json`
```bash
$ curl -i -H "Accept: application/vnd.api+json" http://localhost:8080/articles.json                                                                 
HTTP/1.1 200 
X-Application-Context: application:development
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 04 Oct 2016 19:38:04 GMT

{"data":[{"type":"article","id":"1","attributes":{"title":" ...  }}]}
```
**Behavior:**
The json returned has a `Content-Type` of `application/json`

**Expected Behavior:**
The json returned would have a `Content-Type` of `application/vnd.api+json`

Note: Similar behavior can be observed for `application/hal+json`
Example application: https://github.com/grails-samples/jsonapi-example

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-views/commit/52f3990fc8d13c93fe451af0635b59e559b445bf
