### ISSUE TITLE
JSON API: Includes support

### ISSUE THREAD

**Issue by ColinHarrington** [grails/grails-views#81]
includes support is needed within jsonapi rendering

**Comment by jameskleeh** [comment]
Done.

Test for `associations: Boolean` argument: https://github.com/grails/grails-views/blob/master/json/src/test/groovy/grails/plugin/json/view/IncludeAssociationsSpec.groovy

Tests for `includes: Array` argument: https://github.com/grails/grails-views/blob/master/json/src/test/groovy/grails/plugin/json/view/JsonViewHelperSpec.groovy#L151
