### ISSUE TITLE
Mock view resolvers in unit tests

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-views#87]
At the moment, it's not possible to unit test a controller that responds to a JSON view, as the views are not resolved.

It would be great if the view resolvers could be wired somehow for unit tests. Maybe in `JsonViewTest`.

**Comment by alvarosanchez** [comment]
I can't seem to reproduce it anymore. Closing this issue.

**Comment by kastone** [comment]
I would like to reopen this. I have a sample project to demonstrate that json views are not being resolved in unit tests. https://github.com/kastone/GsonTemplateNotResolved

**Comment by graemerocher** [comment]
As covered in http://guides.grails.org/rest-mongodb/guide/index.html

You need to register the view resolver in the test:

```groovy
static doWithSpring = {
    jsonSmartViewResolver(JsonViewResolver)
}
```

**Comment by jameskleeh** [comment]
Just want to add on to this for others. When testing a controller that calls `respond` without specifying the view, I had to set the action name manually before executing the action.

```
webRequest.actionName = "foo"
controller.foo()
```

**Comment by jameskleeh** [comment]
Fixed in grails-testing-support
