### ISSUE TITLE
Simple lists inside a Map using respond method not working

### ISSUE THREAD

**Issue by sagrawal14** [grails/grails-views#88]
I have a simple controller created with 3.2.0 using rest-api profile:

```groovy
class LoginController {

    static responseFormats = ['json']

    def getData() {
        Map result = [:]
        result.success = true
        result.foo = "bar"
        result.user = User.first()
        result.roles = ["ROLE_ADMIN", "ROLE_USER"]

        respond(result)
    }
}
```

When we hit the endpoint as:

    curl  http://localhost:8080/login/getData -H "accept:application/json" 

I was getting Stackoverflow error related to issue #66 so I upgraded the json-view dependency to 1.1.1 (released [yesterday](https://github.com/grails/grails-views/releases/tag/v1.1.1)). After upgrading that dependency, the API call results me the following output:

```json
{
  "success": true,
  "foo": "bar",
  "user": {
    "id": 1,
    "email": "john@example.com",
    "name": "John",
    "organization": {
      "id": 1
    }
  },
  "roles": {}
}
```

The `roles` key with a List is not being rendered properly.

To reproduce the issue, use repo [sagrawal14/jsonview-problem](https://github.com/sagrawal14/jsonview-problem) and the [2nd commit](https://github.com/sagrawal14/jsonview-problem/commit/9e08cd40297f950cf44b21e830c270bbf674ff33) which has the actual changes.

**Comment by sagrawal14** [comment]
Any workaround on this? Removing `views/object/_object.gson` seems to be working temporarily.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-views/commit/38e5d2d215a67557068f0de359817fe4e14e15f4

**Comment by sagrawal14** [comment]
@jameskleeh Any workaround for this issue till the new version is released. Although removing `_object.gson` making it work but then it is breaking the json view template by convention i.e. if I add `grails-app/views/user/_user.gson` for the above example, that template will not be used after removing `_object.gson`.

**Comment by jameskleeh** [comment]
Correct, because by removing the `_object.gson` you are no longer using json views. I don't believe there is a workaround until the next version is released other than to manually create the json with a `/login/getData.gson`

**Comment by sagrawal14** [comment]
Alright, thanks @jameskleeh. Do you have any estimated timeline for the release?
