### ISSUE TITLE
gson cache

### ISSUE THREAD

**Issue by barcelona23** [grails/grails-views#9]
Using rest-api profile with grails 3.1.2.
Each change on gson files I have to stop the app and then run it again.
Not sure If I missing something.

According to the latest doc, I using this in application.yml
grails:
  views:
    json:
      compileStatic: false
      cache: false
      enableReloading: true
      cacheTemplates: false
      autoIndent: true

Any thought?

**Comment by graemerocher** [comment]
Don't know the exact cause, but probably fixed by https://github.com/grails/grails-views/commit/200895610f125a3bba93116979d24fc96ccc316c
