### ISSUE TITLE
Customize default Date rendering to json

### ISSUE THREAD

**Issue by Uniqen** [grails/grails-views#92]
I would like to be able to customize the format used in Date rendering (include milliseconds). 
In grails.pluginJsonOutput.java it's right now hard coded to
`private static final String JSON_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss'Z'";`

The only workaround I could think of was to duplicate the class and place in my src-folder with JSON_DATE_FORMAT set to my preferred value.

**Comment by andreasschiestl** [comment]
Maybe something linke g.formatDate will be useful

**Comment by Uniqen** [comment]
Updated the title to clarify that its the default date rendering I would like to customize. Since Date is handled by JsonOutput.java it is not possible to use global templates for this.

**Comment by jameskleeh** [comment]
Possible in 1.2
